const CACHE="last-horizon-11.0.0-full-media-audio";
const AVATARS=["amara-diallo","asha-rao","elias-brandt","imani-okafor","jun-park","lena-volkov","malik-okoye","mateo-vega","nayara-quispe","rafael-costa","samira-haddad"];
const SCENES=["mission-control","integration-bay","flight-deck","flight-deck-v2","launch-pad","deep-cruise","aurelia-colony","orbital-operations"];
const MEDIA=[...AVATARS.flatMap(name=>[`./assets/images/avatars/${name}.webp`,`./assets/images/avatars/${name}.png`]),...SCENES.flatMap(name=>[`./assets/images/scenes/${name}.webp`,`./assets/images/scenes/${name}.png`])];
const CORE=["./","./index.html","./404.html","./manifest.webmanifest","./version.json?v=11.0.0","./styles/tokens.css","./styles/base.css","./styles/layout.css","./styles/components.css?v=11","./styles/screens.css?v=16","./styles/accessibility.css","./src/app.js?v=11.0.0","./src/core/store.js","./src/core/rng.js","./src/data/save-manager.js","./src/sim/simulation.js","./src/sim/orbital.js","./src/sim/flight-dynamics.js","./src/sim/solar-system.js","./src/sim/mission-operations.js","./src/sim/rendezvous.js","./src/ui/router.js","./src/ui/astronomy.js","./src/ui/flight-3d.js","./src/ui/flight-tutorial.js","./src/ui/mission-operations.js","./src/ui/planet-surface.js","./src/ui/rendezvous.js","./src/ui/cinematic-director.js","./src/audio/flight-audio.js","./src/audio/music-director.js","./data/game.json","./data/locales.json?v=11.0.0","./data/story.json?v=11.0.0","./data/engineering.json?v=11.0.0","./data/crew-operations.json?v=11.0.0","./data/solar-system.json?v=11.0.0","./assets/video/video-manifest.json?v=11.0.0","./assets/video/flight-manifest.json?v=11.0.0","./assets/video/cinematic-manifest.json?v=11.0.0","./assets/audio/voice-manifest.json?v=11.0.0","./assets/audio/music-manifest.json?v=11.0.0","./assets/icons/icon.svg","./assets/images/real/earth-blue-marble-2048.jpg","./assets/images/brand/bg-main-menu-earth-orbit.webp","./assets/images/brand/bg-main-menu-earth-orbit.png",...MEDIA];
self.addEventListener("install",event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener("activate",event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(async()=>{await self.clients.claim();const windows=await self.clients.matchAll({type:"window"});await Promise.all(windows.map(client=>client.navigate(client.url)))})));
self.addEventListener("fetch",event=>{
  if(event.request.method!=="GET")return;
  if(event.request.destination==="video")return;
  event.respondWith(caches.match(event.request).then(hit=>hit||fetch(event.request).then(response=>{if(response.ok&&new URL(event.request.url).origin===location.origin){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response}).catch(()=>event.request.mode==="navigate"?caches.match("./index.html"):Response.error())));
});
