import test from "node:test";
import assert from "node:assert/strict";
import {createInitialState} from "../src/core/store.js";
import {checksum,migrate,migrateV10,migrateV11,migrateV12,migrateV13,migrateV14} from "../src/data/save-manager.js";
test("checksum changes when state changes",()=>{const a=createInitialState("A"),before=checksum(a);a.economy.available--;assert.notEqual(checksum(a),before)});
test("legacy save migrates without deleting campaign data",()=>{const old={meta:{saveVersion:1},campaign:{act:4},colony:{},ui:null,ship:{design:{propulsion:"nuclear"}},crew:{members:["amara","jun","elias","asha","malik","lena"],training:1},mission:{flightStage:0}};const next=migrate(old);assert.equal(next.meta.saveVersion,8);assert.equal(next.campaign.act,4);assert.equal(next.campaign.turn,1);assert.equal(next.ui.tutorialEnabled,true);assert.deepEqual(next.colony.research,[]);assert.deepEqual(next.engineering.locked,["propulsion"]);assert.equal(Object.values(next.crew.assignments).filter(Boolean).length,6);assert.equal(next.crew.trainingModules.length,3);assert.equal(next.crew.legacyCertified,true);assert.equal(next.engineering.recoveryCount,0);assert.equal(next.mission.orbit.body,"Terra");assert.equal(next.astronomy.selectedBody,"earth");assert.ok(next.science)});
test("current migration adds endless operations without resetting the campaign",()=>{const old=createInitialState("SAVE-V10");delete old.operations;old.meta.saveVersion=9;old.campaign.act=8;const next=migrateV10(old);assert.equal(next.meta.saveVersion,10);assert.equal(next.campaign.act,8);assert.equal(next.operations.board.length,3);assert.equal(next.operations.completed.length,0)});
test("version 11 migration adds rendezvous and media state without resetting progress",()=>{const old=createInitialState("SAVE-V11");delete old.mission.rendezvous;delete old.cinematics;old.meta.saveVersion=10;old.campaign.act=9;const next=migrateV11(old);assert.equal(next.meta.saveVersion,11);assert.equal(next.campaign.act,9);assert.equal(next.mission.rendezvous.status,"ready");assert.deepEqual(next.cinematics.played,[])});

test("version 12 migration adds independent audio channels without resetting progress",()=>{const old=createInitialState("SAVE-V12");delete old.profile.audioMix;old.meta.saveVersion=11;old.campaign.act=10;const next=migrateV12(old);assert.equal(next.meta.saveVersion,12);assert.equal(next.campaign.act,10);assert.deepEqual(next.profile.audioMix,{music:22,voices:90,effects:56})});
test("version 13 migration recovers a cinematic-paused flight and adds navigation",()=>{const old=createInitialState("SAVE-V13");delete old.mission.navigation;old.mission.flight6d.status="ascent";old.mission.flight6d.paused=true;old.mission.flight6d.pauseReason="ignition-cinematic";old.meta.saveVersion=12;const next=migrateV13(old);assert.equal(next.meta.saveVersion,13);assert.equal(next.mission.flight6d.paused,false);assert.equal(next.mission.flight6d.pauseReason,null);assert.equal(next.mission.navigation.controlMode,"command")});
test("version 14 migration adds first-flight training without reopening it after orbit",()=>{const old=createInitialState("SAVE-V14");delete old.mission.flightTraining;old.meta.saveVersion=13;old.mission.flightStage=0;const active=migrateV14(old);assert.equal(active.meta.saveVersion,14);assert.equal(active.mission.flightTraining.status,"active");const flown=createInitialState("SAVE-V14-FLOWN");delete flown.mission.flightTraining;flown.meta.saveVersion=13;flown.mission.flightStage=3;const completed=migrateV14(flown);assert.equal(completed.mission.flightTraining.status,"completed")});
