import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {createInitialState} from "../src/core/store.js";
import {recalculate,commitEngineeringDecision,reopenEngineeringDecision,authorizeEngineeringRecovery,assignCrewMember,completeCrewTraining,recoverCrewFatigue,completeTest,simulateLaunch,advanceCruise,scanPlanet,buildColony,endingFor} from "../src/sim/simulation.js";
const data=JSON.parse(await readFile(new URL("../data/game.json",import.meta.url),"utf8"));
const engineering=JSON.parse(await readFile(new URL("../data/engineering.json",import.meta.url),"utf8"));
const crewOps=JSON.parse(await readFile(new URL("../data/crew-operations.json",import.meta.url),"utf8"));

test("same seed produces the same critical launch result",()=>{
  const prepare=()=>{const s=createInitialState("REPEATABLE-42");s.ship.design={propulsion:"nuclear",habitat:"dual",power:"hybrid",shield:"water"};s.mission.testsCompleted=["bench","vibration","vacuum","software"];s.mission.testGain=13;s.crew.members=data.crew.slice(0,6).map(c=>c.id);return recalculate(s,data)};
  const a=prepare(),b=prepare();assert.deepEqual(simulateLaunch(a),simulateLaunch(b));assert.equal(a.meta.rngState,b.meta.rngState);
});
test("integrated design derives mass, power, thermal and delta-v",()=>{const s=createInitialState();s.ship.design={propulsion:"nuclear",habitat:"compact",power:"fission",shield:"light"};recalculate(s,data);assert.equal(s.ship.designValid,true);assert.ok(s.ship.mass.total<43000);assert.ok(s.ship.powerMargin>=80);assert.ok(s.ship.deltaV>=2000)});
test("engineering commitment spends political, financial and schedule resources",()=>{const s=recalculate(createInitialState(),data),session=engineering.sessions[0],option=session.options[0],component=data.components.propulsion.find(x=>x.id===option.componentId),before={budget:s.economy.available,date:s.time.earthDate,influence:s.agency.politicalCapital,trust:s.crew.trust};const result=commitEngineeringDecision(s,data,session,option);recalculate(s,data);assert.equal(result.ok,true);assert.equal(s.economy.available,before.budget-component.cost);assert.equal(s.time.earthDate,before.date+option.days);assert.equal(s.agency.politicalCapital,before.influence+option.influence);assert.equal(s.crew.trust,before.trust+option.trust);assert.deepEqual(s.engineering.locked,["propulsion"]);assert.equal(commitEngineeringDecision(s,data,session,option).ok,false)});
test("reopening a signed engineering contract has sunk cost",()=>{const s=recalculate(createInitialState(),data),session=engineering.sessions[0],option=session.options[0];commitEngineeringDecision(s,data,session,option);const before={budget:s.economy.available,committed:s.economy.committed,date:s.time.earthDate};const result=reopenEngineeringDecision(s,"propulsion");assert.equal(result.ok,true);assert.equal(s.ship.design.propulsion,null);assert.equal(s.economy.available,before.budget-3);assert.equal(s.economy.committed,before.committed+3);assert.equal(s.time.earthDate,before.date+18);assert.equal(s.engineering.revisionCount,1)});
test("engineering contingency recovers a resource-locked proposal with consequences",()=>{const s=recalculate(createInitialState(),data),session=engineering.sessions[1],option=session.options[1],component=data.components.habitat.find(x=>x.id===option.componentId);s.economy.available=0;s.economy.contingency=5;s.agency.politicalCapital=0;const beforeSupport=s.agency.support,result=authorizeEngineeringRecovery(s,component,option);assert.equal(result.ok,true);assert.equal(s.economy.available,component.cost);assert.ok(result.bond>0);assert.ok(s.agency.support<beforeSupport);assert.ok(s.time.earthDate>0);assert.equal(s.engineering.recoveryCount,1)});
test("a guided engineering path remains certifiable with test reserve",()=>{const s=recalculate(createInitialState(),data),choices={propulsion:"nuclear",habitat:"compact",power:"fission",shield:"light"};for(const session of engineering.sessions){const option=session.options.find(x=>x.componentId===choices[session.id]);assert.equal(commitEngineeringDecision(s,data,session,option).ok,true);recalculate(s,data)}assert.equal(s.ship.designValid,true);assert.ok(s.economy.available>=14);assert.ok(s.time.earthDate<3650)});
test("crew assignment requires interview and one person cannot occupy two stations",()=>{const s=recalculate(createInitialState(),data,crewOps);assert.equal(assignCrewMember(s,"engineering","lena",crewOps).ok,false);s.crew.interviewed.push("lena");assert.equal(assignCrewMember(s,"engineering","lena",crewOps).ok,true);assert.equal(assignCrewMember(s,"operations","lena",crewOps).ok,true);assert.equal(s.crew.assignments.engineering,null);assert.equal(s.crew.assignments.operations,"lena")});
test("six stations and three training modules certify an operational crew",()=>{const s=recalculate(createInitialState(),data,crewOps),roster={command:"amara",flight:"jun",engineering:"elias",medical:"asha",science:"malik",operations:"lena"};s.crew.interviewed=Object.values(roster);for(const [station,id] of Object.entries(roster))assert.equal(assignCrewMember(s,station,id,crewOps).ok,true);for(const module of crewOps.training)assert.equal(completeCrewTraining(s,module).ok,true);recalculate(s,data,crewOps);assert.equal(s.mission.checklists.crew,true);assert.equal(s.crew.members.length,6);assert.ok(s.crew.cohesion>=70);assert.equal(s.economy.available,115)});
test("cruise accumulates role fatigue and rest rotation reduces it",()=>{const s=recalculate(createInitialState(),data,crewOps),roster={command:"amara",flight:"jun",engineering:"elias",medical:"asha",science:"malik",operations:"lena"};s.crew.interviewed=Object.values(roster);for(const [station,id] of Object.entries(roster))assignCrewMember(s,station,id,crewOps);const before=s.crew.fatigue.elias;advanceCruise(s,data);assert.ok(s.crew.fatigue.elias>before);const tired=s.crew.fatigue.elias;assert.equal(recoverCrewFatigue(s),true);assert.ok(s.crew.fatigue.elias<tired)});
test("fatigue and low cohesion increase causal launch risk",()=>{const low=recalculate(createInitialState("CREW-RISK"),data,crewOps);low.ship.reliability=95;low.ship.designValid=true;low.mission.checklists.tests=true;low.crew.cohesion=88;low.crew.fatigue={a:0,b:0,c:0};const high=structuredClone(low);high.crew.cohesion=52;high.crew.fatigue={a:90,b:90,c:90};const nominal=simulateLaunch(low),degraded=simulateLaunch(high);assert.ok(degraded.risk>nominal.risk)});
test("tests spend budget and improve evidence",()=>{const s=recalculate(createInitialState(),data),before=s.economy.available;completeTest(s,data.tests[0]);recalculate(s,data);assert.equal(s.economy.available,before-data.tests[0].cost);assert.equal(s.mission.testsCompleted.length,1);assert.ok(s.mission.testGain>=data.tests[0].gain)});
test("planet labels are confidence weighted",()=>{const s=createInitialState();const first=scanPlanet(s,data.planets[0]);assert.equal(first.confidence,34);assert.ok(first.habitability<50);const second=scanPlanet(s,data.planets[0]);assert.equal(second.confidence,68);assert.ok(second.habitability>first.habitability)});
test("colony construction has finite resources and dependencies remain observable",()=>{const s=createInitialState();const before=s.colony.resources.materials;assert.equal(buildColony(s,data.buildings[0]),true);assert.equal(s.colony.resources.materials,before-data.buildings[0].cost);assert.equal(buildColony(s,data.buildings[0]),false)});
test("ending explains state-derived outcome",()=>{const s=createInitialState();s.mission.route.target="aurelia";s.science.targets.aurelia={confidence:75};s.ship.integrity=95;s.crew.morale=90;s.ship.capacity=100;s.colony.founded=true;s.colony.buildings=data.buildings.slice(0,5).map(b=>b.id);s.colony.research=["closed-loop","autofab"];s.colony.governance.policy="council";const ending=endingFor(s);assert.equal(ending.id,"dawn");assert.ok(ending.scores.survival>=78)});
