import {planetaryPositions,distanceBetween,earthSunDirection,missionDate,formatDistance,LIGHT_SECONDS_PER_AU} from "../sim/solar-system.js";

let activeCleanup=null;
const clean=()=>{activeCleanup?.();activeCleanup=null};
export const unmountAstronomy=clean;
const isoDay=date=>date.toISOString().slice(0,10);

export function astronomyView(state,solarData,esc=value=>String(value)){
  const astronomy=state.astronomy||{},mode=astronomy.view||"earth",date=missionDate(state),positions=planetaryPositions(date,solarData);
  const earth=positions.find(body=>body.id==="earth"),selected=positions.find(body=>body.id===(astronomy.selectedBody||"earth"))||earth;
  const separation=selected.id==="earth"?0:distanceBetween(earth,selected);
  return `<section class="astro-suite">
    <header class="astro-command-head"><div><div class="eyebrow">OBSERVATÓRIO DE NAVEGAÇÃO · DADOS JPL / NASA</div><h1>Atlas do Sistema Solar</h1><p>Posições heliocêntricas calculadas para a data da missão. O mapa e o globo continuam funcionando sem internet.</p></div><div class="astro-clock"><span>TEMPO EFEMÉRIDE UTC</span><b data-astro-clock>${esc(date.toISOString().replace(".000Z","Z"))}</b><small>Modelo aproximado J2000 · válido 1800–2050</small></div></header>
    <div class="astro-tabs" role="tablist"><button class="${mode==="earth"?"active":""}" data-astro-view="earth">GLOBO TERRESTRE</button><button class="${mode==="solar"?"active":""}" data-astro-view="solar">MAPA DO SISTEMA SOLAR</button></div>
    <div class="astro-toolbar"><label>DATA UTC<input type="date" min="1800-01-01" max="2050-12-31" value="${isoDay(date)}" data-astro-date></label><button data-date-step="-30">−30 DIAS</button><button data-date-step="-1">−1 DIA</button><button data-date-now>DATA DA MISSÃO</button><button data-date-step="1">+1 DIA</button><button data-date-step="30">+30 DIAS</button><button class="primary" data-time-play>▶ PROPAGAR</button></div>
    ${mode==="earth"?earthPanel(state,solarData,date):solarPanel(state,solarData,date,positions,selected,separation)}
  </section>`;
}

function earthPanel(state,solarData,date){
  const siteId=state.astronomy?.launchSite||"alcantara",site=solarData.launchSites.find(item=>item.id===siteId)||solarData.launchSites[0];
  return `<div class="earth-observatory"><section class="earth-stage panel"><div class="earth-canvas-stack"><canvas id="earth-globe" aria-label="Globo terrestre interativo com textura Blue Marble da NASA"></canvas><canvas id="earth-sites" aria-hidden="true"></canvas><div class="earth-hud-corners"></div></div><div class="earth-instructions"><span>ARRASTE PARA GIRAR</span><span>RODA DO MOUSE PARA APROXIMAR</span><span>ILUMINAÇÃO SOLAR CALCULADA</span></div><div class="earth-credit">TEXTURA · NASA BLUE MARBLE / MODIS</div></section>
  <aside class="earth-console"><section class="panel panel-pad"><div class="eyebrow">CORREDOR DE LANÇAMENTO</div><h2>${site.name}</h2><p>${site.note}</p><div class="coordinate-grid"><span><small>LATITUDE</small><b>${Math.abs(site.lat).toFixed(3)}° ${site.lat<0?"S":"N"}</b></span><span><small>LONGITUDE</small><b>${Math.abs(site.lon).toFixed(3)}° ${site.lon<0?"W":"E"}</b></span><span><small>DATA</small><b>${isoDay(date)}</b></span><span><small>ROTAÇÃO</small><b>sidérea</b></span></div></section><section class="panel launch-site-list"><div class="eyebrow">REDE GLOBAL GSEA</div>${solarData.launchSites.map(item=>`<button class="${item.id===site.id?"selected":""}" data-launch-site="${item.id}"><i></i><span><b>${item.name}</b><small>${item.country} · ${item.lat.toFixed(2)}°, ${item.lon.toFixed(2)}°</small></span></button>`).join("")}</section><section class="expert-note"><div class="expert-note-avatar"><img src="./assets/images/avatars/jun-park.webp" alt="Jun Park"></div><div><span>JUN PARK · NAVEGAÇÃO</span><p>“O planeta não é cenário. Latitude, rotação e direção prógrada alteram energia, inclinação e corredor de segurança.”</p></div></section></aside></div>`;
}

function solarPanel(state,solarData,date,positions,selected,separation){
  const scale=state.astronomy?.scale||"log";
  return `<div class="solar-observatory"><section class="solar-stage panel"><canvas id="solar-map" aria-label="Mapa interativo do Sistema Solar em coordenadas heliocêntricas J2000"></canvas><div class="solar-legend"><span><i class="sun-dot"></i>SOL</span><span><i class="planet-dot"></i>PLANETAS</span><span><i class="ark-dot"></i>ARK-01 / ROTA</span></div><div class="solar-scale"><button class="${scale==="log"?"active":""}" data-solar-scale="log">ESCALA LOG</button><button class="${scale==="linear"?"active":""}" data-solar-scale="linear">ESCALA LINEAR</button></div></section><aside class="solar-console"><section class="body-dossier panel panel-pad"><div class="body-title"><span class="body-symbol" style="--body:${selected.color}">${selected.symbol}</span><div><div class="eyebrow">CORPO SELECIONADO</div><h2>${selected.name}</h2></div></div><p>${selected.description}</p><div class="coordinate-grid body-metrics"><span><small>DISTÂNCIA DO SOL</small><b data-selected-distance>${formatDistance(selected.distanceAu)}</b></span><span><small>DISTÂNCIA DA TERRA</small><b data-earth-distance>${selected.id==="earth"?"ORIGEM":formatDistance(separation)}</b></span><span><small>TEMPO-LUZ</small><b data-light-time>${selected.id==="earth"?"0 s":`${(separation*LIGHT_SECONDS_PER_AU/60).toFixed(1)} min`}</b></span><span><small>LONG. ECLÍPTICA</small><b data-selected-longitude>${selected.longitudeDeg.toFixed(2)}°</b></span><span><small>RAIO MÉDIO</small><b>${selected.radiusKm.toLocaleString("pt-BR")} km</b></span><span><small>GRAVIDADE</small><b>${selected.gravityMs2.toFixed(2)} m/s²</b></span><span><small>DIA SIDÉREO</small><b>${Math.abs(selected.dayHours).toLocaleString("pt-BR")} h${selected.dayHours<0?" retrógrado":""}</b></span><span><small>ANO</small><b>${selected.yearDays.toLocaleString("pt-BR")} dias</b></span></div></section><section class="planet-selector panel"><div class="eyebrow">ALVOS DE NAVEGAÇÃO</div>${positions.map(body=>`<button class="${body.id===selected.id?"selected":""}" data-select-body="${body.id}"><i style="--body:${body.color}"></i><span>${body.name}</span><b data-body-distance="${body.id}">${body.distanceAu.toFixed(2)} UA</b></button>`).join("")}</section><section class="model-status"><span>MODELO ATIVO</span><b>KEPLER + ELEMENTOS JPL</b><p>Este atlas usa aproximação de dois corpos. Perturbações N-corpos e efemérides operacionais exigiriam SPICE/Horizons.</p></section></aside></div>`;
}

export function mountAstronomy({root,getState,solarData,updateAstronomy,toast}){
  clean();
  const abort=new AbortController(),signal=abort.signal,listen=(element,event,handler,options={})=>element?.addEventListener(event,handler,{...options,signal});
  const state=getState(),date=missionDate(state),mode=state.astronomy?.view||"earth";
  root.querySelectorAll("[data-astro-view]").forEach(button=>listen(button,"click",()=>updateAstronomy({view:button.dataset.astroView},"Visão do observatório alterada")));
  root.querySelectorAll("[data-date-step]").forEach(button=>listen(button,"click",()=>{const next=missionDate(getState());next.setUTCDate(next.getUTCDate()+Number(button.dataset.dateStep));updateAstronomy({dateIso:next.toISOString()},"Efeméride propagada")}));
  listen(root.querySelector("[data-date-now]"),"click",()=>{const next=new Date(Date.UTC(2047,0,1,12));next.setUTCDate(next.getUTCDate()+(getState().time?.earthDate||0));updateAstronomy({dateIso:next.toISOString()},"Efeméride sincronizada à missão")});
  listen(root.querySelector("[data-astro-date]"),"change",event=>updateAstronomy({dateIso:new Date(`${event.target.value}T12:00:00Z`).toISOString()},"Data astronômica definida"));
  root.querySelectorAll("[data-launch-site]").forEach(button=>listen(button,"click",()=>updateAstronomy({launchSite:button.dataset.launchSite},"Corredor de lançamento selecionado")));
  root.querySelectorAll("[data-solar-scale]").forEach(button=>listen(button,"click",()=>updateAstronomy({scale:button.dataset.solarScale},"Escala do mapa alterada")));
  root.querySelectorAll("[data-select-body]").forEach(button=>listen(button,"click",()=>updateAstronomy({selectedBody:button.dataset.selectBody},`Alvo astronômico selecionado: ${button.dataset.selectBody}`)));
  let playing=false,workingDate=new Date(date),last=performance.now(),animation=0,renderer=null;
  const playButton=root.querySelector("[data-time-play]");
  const persistTime=()=>updateAstronomy({dateIso:workingDate.toISOString()},"Propagação temporal pausada");
  const frame=now=>{if(!playing)return;const delta=Math.min(100,now-last);last=now;workingDate=new Date(workingDate.getTime()+delta*864000);updateDynamicAstronomy(root,getState(),solarData,workingDate,renderer);animation=requestAnimationFrame(frame)};
  listen(playButton,"click",()=>{playing=!playing;playButton.textContent=playing?"Ⅱ PAUSAR":"▶ PROPAGAR";playButton.classList.toggle("danger",playing);if(playing){last=performance.now();animation=requestAnimationFrame(frame)}else persistTime()});
  if(mode==="earth")renderer=createEarthRenderer(root,solarData,date,getState,toast);else renderer=createSolarRenderer(root,solarData,date,getState,body=>updateAstronomy({selectedBody:body},`Alvo astronômico selecionado: ${body}`));
  activeCleanup=()=>{abort.abort();cancelAnimationFrame(animation);renderer?.destroy?.()};
}

function updateDynamicAstronomy(root,state,solarData,date,renderer){
  const positions=planetaryPositions(date,solarData),earth=positions.find(body=>body.id==="earth"),selected=positions.find(body=>body.id===(state.astronomy?.selectedBody||"earth"))||earth,separation=distanceBetween(earth,selected);
  const clock=root.querySelector("[data-astro-clock]");if(clock)clock.textContent=date.toISOString().replace(".000Z","Z");
  const dateInput=root.querySelector("[data-astro-date]");if(dateInput)dateInput.value=isoDay(date);
  const set=(selector,value)=>{const element=root.querySelector(selector);if(element)element.textContent=value};
  set("[data-selected-distance]",formatDistance(selected.distanceAu));set("[data-earth-distance]",selected.id==="earth"?"ORIGEM":formatDistance(separation));set("[data-light-time]",selected.id==="earth"?"0 s":`${(separation*LIGHT_SECONDS_PER_AU/60).toFixed(1)} min`);set("[data-selected-longitude]",`${selected.longitudeDeg.toFixed(2)}°`);
  positions.forEach(body=>set(`[data-body-distance="${body.id}"]`,`${body.distanceAu.toFixed(2)} UA`));
  renderer?.update?.(date,positions);
}

function createEarthRenderer(root,solarData,date,getState,toast){
  const canvas=root.querySelector("#earth-globe"),overlay=root.querySelector("#earth-sites");if(!canvas)return null;
  const gl=canvas.getContext("webgl",{alpha:true,antialias:true,premultipliedAlpha:false});
  if(!gl){canvas.classList.add("earth-fallback");toast?.("WebGL indisponível: exibindo o globo em modo compatível.","error");return createEarthFallback(canvas,overlay,solarData,getState)}
  const vertex=`attribute vec2 p;varying vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`;
  const fragment=`precision mediump float;varying vec2 uv;uniform sampler2D tex;uniform vec2 view;uniform vec3 sun;uniform float aspect;uniform float zoom;void main(){vec2 q=uv*2.-1.;q.x*=aspect;q/=zoom;float r2=dot(q,q);if(r2>1.)discard;float z=sqrt(max(0.,1.-r2));vec3 n=vec3(q.x,q.y,z);float cp=cos(view.y),sp=sin(view.y);n=vec3(n.x,cp*n.y-sp*n.z,sp*n.y+cp*n.z);float cy=cos(view.x),sy=sin(view.x);n=vec3(cy*n.x+sy*n.z,n.y,-sy*n.x+cy*n.z);float lon=atan(n.x,n.z);float lat=asin(clamp(n.y,-1.,1.));vec3 map=texture2D(tex,vec2(fract(lon/6.2831853+.5),.5-lat/3.1415926)).rgb;float daylight=max(dot(n,sun),0.);float light=.105+.895*smoothstep(-.08,.22,daylight);float limb=pow(1.-z,2.2);vec3 atmosphere=vec3(.12,.52,.95)*limb*(.28+.72*daylight);vec3 color=map*light+atmosphere;float alpha=smoothstep(1.,.965,r2);gl_FragColor=vec4(color,alpha);}`;
  const shader=(type,source)=>{const result=gl.createShader(type);gl.shaderSource(result,source);gl.compileShader(result);if(!gl.getShaderParameter(result,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(result));return result};
  const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vertex));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(program);gl.useProgram(program);
  const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const position=gl.getAttribLocation(program,"p");gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,2,gl.FLOAT,false,0,0);
  const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([20,70,110,255]));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
  let yaw=-44*Math.PI/180,pitch=-8*Math.PI/180,zoom=.86,currentDate=new Date(date),positions=planetaryPositions(date,solarData),drag=null;
  const image=new Image();image.src=solarData.texture.src;image.onload=()=>{gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,image);render()};
  const size=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(2,Math.round(rect.width*dpr)),h=Math.max(2,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;overlay.width=w;overlay.height=h}gl.viewport(0,0,w,h);return {rect,dpr,w,h}};
  const render=()=>{const {w,h,dpr}=size(),earth=positions.find(body=>body.id==="earth"),solar=earthSunDirection(currentDate,earth),sun=[solar[1],solar[2],solar[0]];gl.useProgram(program);gl.uniform2f(gl.getUniformLocation(program,"view"),yaw,pitch);gl.uniform3fv(gl.getUniformLocation(program,"sun"),sun);gl.uniform1f(gl.getUniformLocation(program,"aspect"),w/h);gl.uniform1f(gl.getUniformLocation(program,"zoom"),zoom);gl.drawArrays(gl.TRIANGLES,0,6);drawSites(overlay,solarData.launchSites,getState().astronomy?.launchSite,yaw,pitch,zoom,dpr)};
  canvas.addEventListener("pointerdown",event=>{drag={x:event.clientX,y:event.clientY,yaw,pitch};canvas.setPointerCapture(event.pointerId)});
  canvas.addEventListener("pointermove",event=>{if(!drag)return;yaw=drag.yaw+(event.clientX-drag.x)*.008;pitch=Math.max(-1.25,Math.min(1.25,drag.pitch-(event.clientY-drag.y)*.008));render()});
  canvas.addEventListener("pointerup",()=>drag=null);canvas.addEventListener("wheel",event=>{event.preventDefault();zoom=Math.max(.62,Math.min(.98,zoom-event.deltaY*.0005));render()},{passive:false});
  const resize=()=>render();addEventListener("resize",resize);render();
  return {update(nextDate,nextPositions){currentDate=new Date(nextDate);positions=nextPositions;render()},destroy(){removeEventListener("resize",resize);gl.deleteProgram(program);gl.deleteTexture(texture);gl.deleteBuffer(buffer)}};
}

function drawSites(canvas,sites,selected,yaw,pitch,zoom,dpr){
  const ctx=canvas.getContext("2d"),w=canvas.width/dpr,h=canvas.height/dpr,aspect=w/h,radius=h*.5*zoom;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);for(const site of sites){const lat=site.lat*Math.PI/180,lon=site.lon*Math.PI/180;let x=Math.sin(lon)*Math.cos(lat),y=Math.sin(lat),z=Math.cos(lon)*Math.cos(lat);const cy=Math.cos(-yaw),sy=Math.sin(-yaw),x1=cy*x+sy*z,z1=-sy*x+cy*z;const cp=Math.cos(-pitch),sp=Math.sin(-pitch),y1=cp*y-sp*z1,z2=sp*y+cp*z1;if(z2<=0)continue;const px=w/2+x1*radius,py=h/2-y1*radius,isSelected=site.id===selected;ctx.strokeStyle=isSelected?"#ffb84c":"rgba(110,230,255,.8)";ctx.fillStyle=isSelected?"#ffb84c":"#84ecff";ctx.lineWidth=isSelected?2:1;ctx.beginPath();ctx.arc(px,py,isSelected?6:3,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(px,py,isSelected?12:7,0,Math.PI*2);ctx.stroke();if(isSelected){ctx.font="10px ui-monospace,monospace";ctx.fillText(site.name.toUpperCase(),px+16,py+4)}}
}

function createEarthFallback(canvas,overlay,solarData,getState){const render=()=>{const fit=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=fit.width*dpr;canvas.height=fit.height*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);const r=Math.min(fit.width,fit.height)*.4,g=ctx.createRadialGradient(fit.width*.44,fit.height*.4,0,fit.width*.5,fit.height*.5,r);g.addColorStop(0,"#3ec7e8");g.addColorStop(.55,"#0a6594");g.addColorStop(1,"#021421");ctx.fillStyle=g;ctx.beginPath();ctx.arc(fit.width*.5,fit.height*.5,r,0,Math.PI*2);ctx.fill();drawSites(overlay,solarData.launchSites,getState().astronomy?.launchSite,-44*Math.PI/180,-8*Math.PI/180,.8,dpr)};render();return {update:render,destroy(){}}}

function createSolarRenderer(root,solarData,date,getState,onSelect){
  const canvas=root.querySelector("#solar-map"),ctx=canvas?.getContext("2d");if(!canvas||!ctx)return null;let currentDate=new Date(date),positions=planetaryPositions(date,solarData),points=[];
  const render=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(2,Math.round(rect.width*dpr)),h=Math.max(2,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);const W=w/dpr,H=h/dpr,cx=W*.5,cy=H*.5,maxR=Math.min(W,H)*.43,scale=getState().astronomy?.scale||"log",selected=getState().astronomy?.selectedBody||"earth";ctx.clearRect(0,0,W,H);const bg=ctx.createRadialGradient(cx,cy,0,cx,cy,maxR*1.3);bg.addColorStop(0,"#0b2131");bg.addColorStop(1,"#010407");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);for(let i=0;i<120;i++){ctx.fillStyle=`rgba(190,225,255,${.12+(i%7)*.045})`;ctx.fillRect((i*97)%W,(i*53)%H,1,1)}const radial=au=>scale==="linear"?Math.min(maxR,au/30.1*maxR):(18+(maxR-18)*Math.log1p(au*4)/Math.log1p(30.1*4));solarData.bodies.forEach(body=>{ctx.strokeStyle="rgba(76,151,184,.22)";ctx.lineWidth=1;ctx.beginPath();ctx.arc(cx,cy,radial(body.elements.a[0]),0,Math.PI*2);ctx.stroke()});const sun=ctx.createRadialGradient(cx,cy,0,cx,cy,18);sun.addColorStop(0,"#fff9cf");sun.addColorStop(.35,"#ffd254");sun.addColorStop(1,"rgba(255,158,42,0)");ctx.fillStyle=sun;ctx.beginPath();ctx.arc(cx,cy,18,0,Math.PI*2);ctx.fill();points=[];positions.forEach(body=>{const angle=Math.atan2(body.y,body.x),r=radial(body.distanceAu),x=cx+Math.cos(angle)*r,y=cy+Math.sin(angle)*r*.94,size=body.id==="jupiter"?7:body.id==="saturn"?6:body.id==="earth"?5:4;ctx.fillStyle=body.color;ctx.shadowColor=body.color;ctx.shadowBlur=body.id===selected?16:5;ctx.beginPath();ctx.arc(x,y,body.id===selected?size+2:size,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(body.id===selected||body.id==="earth"){ctx.fillStyle="#d9edf3";ctx.font="10px ui-monospace,monospace";ctx.fillText(body.name.toUpperCase(),x+9,y+3)}points.push({id:body.id,x,y,r:13})});const mission=getState().mission;if(getState().campaign?.flags?.launched||mission?.route?.progress>0){const earthPoint=points.find(point=>point.id==="earth"),progress=Math.min(1,(mission.route?.progress||1)/100),angle=Math.atan2(earthPoint.y-cy,earthPoint.x-cx)-.35,endR=radial(1+progress*6);ctx.setLineDash([5,6]);ctx.strokeStyle="#ffb84c";ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(earthPoint.x,earthPoint.y);ctx.quadraticCurveTo(cx+Math.cos(angle+.35)*endR*.65,cy+Math.sin(angle+.35)*endR*.65,cx+Math.cos(angle)*endR,cy+Math.sin(angle)*endR);ctx.stroke();ctx.setLineDash([])}};
  const click=event=>{const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,hit=points.find(point=>Math.hypot(point.x-x,point.y-y)<=point.r);if(hit)onSelect(hit.id)};canvas.addEventListener("click",click);const resize=()=>render();addEventListener("resize",resize);render();return {update(nextDate,nextPositions){currentDate=new Date(nextDate);positions=nextPositions;render()},destroy(){canvas.removeEventListener("click",click);removeEventListener("resize",resize)}};
}
