import {planetaryPositions,planetOrbitPath,missionDate,AU_KM} from "../sim/solar-system.js";
import {ensureNavigationState} from "../sim/interplanetary.js";

const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,value));
const safe=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const mapViews={inner:{label:"PLANETAS INTERNOS",maxAu:2.15,stepAu:.25},giants:{label:"ATÉ SATURNO",maxAu:10.8,stepAu:2},system:{label:"SISTEMA COMPLETO",maxAu:31.5,stepAu:5}};
const layoutCache=new WeakMap();

export function navigationPlannerView(state,solarData){
  const nav=ensureNavigationState(state),route=nav.route,bodies=solarData.bodies.filter(body=>body.id!=="earth"),date=missionDate(state),view=mapViews[nav.mapView]||mapViews.inner,progress=Math.round(nav.progress||0),remaining=route?Math.max(0,route.separationKm*(1-progress/100)):0;
  return `<section class="navigation-planner real-navigation"><header><div><div class="eyebrow">GPS HELIOCÊNTRICO · ELEMENTOS JPL/NASA · ECLÍPTICA J2000</div><h2>Mapa real do Sistema Solar</h2><p>As órbitas, posições e distâncias são calculadas para ${date.toLocaleDateString("pt-BR",{timeZone:"UTC"})}. Toque em um planeta ou use a lista; a ARK-01 percorre a transferência conforme o progresso da missão.</p></div><div class="nav-source"><span>${safe(view.label)}</span><b>${nav.locked?"ROTA ASSINADA":"AGUARDANDO CAPITÃO"}</b><small>Modelo local oficial · funciona offline</small></div></header><div class="navigation-map-controls" aria-label="Escala do mapa">${Object.entries(mapViews).map(([id,item])=>`<button class="${nav.mapView===id?"active":""}" data-nav-view="${id}">${item.label}</button>`).join("")}<a href="${safe(solarData.positionSource)}" target="_blank" rel="noreferrer">FONTE JPL ↗</a></div><div class="navigation-layout"><div class="navigation-map-wrap"><canvas id="navigation-map" tabindex="0" aria-label="Mapa heliocêntrico interativo com órbitas e posições reais dos planetas"></canvas><div class="navigation-map-hud"><span>EFEMÉRIDE ${date.toISOString().slice(0,10)} · ESCALA LINEAR ${view.maxAu} UA</span><b>${route?`TERRA → ${safe(route.targetName).toUpperCase()}`:"TOQUE EM UM PLANETA"}</b><small data-nav-progress>ARK-01 · ${progress}%${route?` · RESTAM ${(remaining/1e6).toFixed(1)} milhões km`:""}</small></div><div class="map-legend"><span><i class="current"></i>posição atual</span><span><i class="arrival"></i>posição na chegada</span><span><i class="transfer"></i>transferência estimada</span></div></div><aside><div class="nav-targets">${bodies.map(body=>`<button class="${nav.selectedBody===body.id?"selected":""}" data-nav-target="${body.id}"><i style="--body:${body.color}"></i><span>${body.symbol} ${safe(body.name)}</span><small>${body.elements.a[0].toFixed(3)} UA · ${body.yearDays.toLocaleString("pt-BR")} dias</small></button>`).join("")}</div>${route?routeCard(route,nav):`<div class="nav-empty"><b>Nenhuma rota traçada</b><span>Selecione um planeta. O computador calculará geometria, Hohmann, janela, atraso de comunicação e delta-v sem inventar posições.</span></div>`}</aside></div></section>`;
}

function routeCard(route,nav){const arrival=new Date(route.arrivalDateIso).toLocaleDateString("pt-BR",{timeZone:"UTC"});return `<div class="nav-route-card"><div class="route-verdict"><span>${route.suitabilityLabel}</span><b>${route.targetName}</b><small>CHEGADA NOMINAL ${arrival}</small></div><div class="nav-route-metrics"><span>DISTÂNCIA ATUAL<b>${route.separationAu.toFixed(3)} UA</b></span><span>TRANSFERÊNCIA<b>${route.transferDays.toFixed(0)} dias</b></span><span>ΔV PARTIDA<b>${route.departureDvMps.toFixed(0)} m/s</b></span><span>JANELA DE FASE<b>${route.windowQuality}%</b></span><span>ATRASO DE SINAL<b>${route.communicationDelayMin.toFixed(1)} min</b></span><span>HABITABILIDADE<b>${route.suitability}%</b></span></div><div class="nav-advisor"><img src="./assets/images/avatars/jun-park.webp" alt="Jun Park"><p><b>JUN PARK · NAVEGAÇÃO</b><span>${safe(route.warning)} ${route.phaseErrorDeg>35?`Erro de fase ${route.phaseErrorDeg.toFixed(1)}°: partir agora aumenta custo e incerteza.`:`Erro de fase ${route.phaseErrorDeg.toFixed(1)}°: corredor aceitável para a transferência.`}</span></p></div><button class="primary" data-nav-lock ${nav.locked?"disabled":""}>${nav.locked?"ROTA CONFIRMADA PELO CAPITÃO":"ASSINAR PLANO DE VOO"}</button></div>`}

function transferSamples(route,count=160){const orbit=route?.transferOrbit;if(!orbit)return [];const points=[],p=orbit.aAu*(1-orbit.e*orbit.e);for(let index=0;index<=count;index++){const t=index/count,nu=orbit.startNuRad+t*Math.PI,r=p/(1+orbit.e*Math.cos(nu)),angle=orbit.orientationRad+nu;points.push({x:Math.cos(angle)*r,y:Math.sin(angle)*r,z:0})}return points}

function bodyRadius(body,selected){if(selected)return 7;if(body.id==="earth")return 5.5;return Math.max(3,Math.min(6,2.2+Math.log10(body.radiusKm)*.7))}

export function drawNavigationMap(canvas,state,solarData,{progress}={}){
  if(!canvas)return false;const ctx=canvas.getContext("2d");if(!ctx)return false;const rect=canvas.getBoundingClientRect(),dpr=Math.min(globalThis.devicePixelRatio||1,2),w=Math.max(2,Math.round(rect.width*dpr)),h=Math.max(2,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);const W=w/dpr,H=h/dpr,cx=W*.5,cy=H*.52,maxR=Math.min(W*.46,H*.43),nav=ensureNavigationState(state),view=mapViews[nav.mapView]||mapViews.inner,date=missionDate(state),positions=planetaryPositions(date,solarData),scale=maxR/view.maxAu,project=point=>({x:cx+point.x*scale,y:cy+point.y*scale}),visible=body=>body.elements.a[0]*(1+body.elements.e[0])<=view.maxAu*1.08;
  const bg=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.max(W,H)*.72);bg.addColorStop(0,"#071b2a");bg.addColorStop(.48,"#020910");bg.addColorStop(1,"#000204");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);for(let index=0;index<220;index++){const alpha=.12+(index%9)*.025;ctx.fillStyle=`rgba(210,232,255,${alpha})`;ctx.fillRect((index*131.7)%W,(index*71.3)%H,index%17===0?1.6:.7,index%23===0?1.6:.7)}
  ctx.save();ctx.strokeStyle="#24404d77";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,cy);ctx.lineTo(W,cy);ctx.moveTo(cx,0);ctx.lineTo(cx,H);ctx.stroke();ctx.font="9px ui-monospace,monospace";ctx.fillStyle="#557783";for(let au=view.stepAu;au<=view.maxAu+.001;au+=view.stepAu){const radius=au*scale;ctx.beginPath();ctx.arc(cx,cy,radius,0,Math.PI*2);ctx.stroke();if(radius<maxR-8)ctx.fillText(`${Number(au.toFixed(2))} UA`,cx+radius+3,cy-3)}ctx.restore();
  solarData.bodies.filter(visible).forEach(body=>{const path=planetOrbitPath(body,date,180);ctx.strokeStyle=body.id===nav.selectedBody?`${body.color}88`:"#43708255";ctx.lineWidth=body.id===nav.selectedBody?1.8:.8;ctx.beginPath();path.forEach((point,index)=>{const p=project(point);if(index)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y)});ctx.stroke()});
  ctx.fillStyle="#fff0a4";ctx.shadowColor="#ffb629";ctx.shadowBlur=24;ctx.beginPath();ctx.arc(cx,cy,9,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#ffeac0";ctx.font="700 9px ui-monospace,monospace";ctx.fillText("SOL",cx+13,cy-9);
  const screenPoints=[];positions.filter(visible).forEach(body=>{const p=project(body);screenPoints.push({...p,id:body.id});const selected=body.id===nav.selectedBody,radius=bodyRadius(body,selected);ctx.fillStyle=body.color;ctx.shadowColor=body.color;ctx.shadowBlur=selected?20:7;ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=selected?"#fff":"#a7d4e177";ctx.lineWidth=selected?2:1;ctx.beginPath();ctx.arc(p.x,p.y,radius+3,0,Math.PI*2);ctx.stroke();ctx.fillStyle=selected?"#fff":"#a9c6d0";ctx.font=`${selected?"700 ":""}9px ui-monospace,monospace`;ctx.fillText(body.name.toUpperCase(),p.x+radius+7,p.y-7);ctx.fillStyle="#6e929f";ctx.font="8px ui-monospace,monospace";ctx.fillText(`${body.distanceAu.toFixed(3)} UA`,p.x+radius+7,p.y+5)});
  if(nav.route){const samples=transferSamples(nav.route),visibleSamples=samples.filter(point=>Math.hypot(point.x,point.y)<=view.maxAu*1.12);ctx.strokeStyle=nav.locked?"#ffbf57":"#5de7ff";ctx.lineWidth=2.4;ctx.setLineDash(nav.locked?[]:[7,5]);ctx.beginPath();visibleSamples.forEach((point,index)=>{const p=project(point);if(index)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y)});ctx.stroke();ctx.setLineDash([]);const targetArrival=project(nav.route.targetArrival||nav.route.target),end=project(samples.at(-1)||nav.route.target);if(Math.hypot((nav.route.targetArrival||nav.route.target).x,(nav.route.targetArrival||nav.route.target).y)<=view.maxAu*1.12){ctx.strokeStyle="#e58dff99";ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(end.x,end.y);ctx.lineTo(targetArrival.x,targetArrival.y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle="#e58dff";ctx.beginPath();ctx.arc(targetArrival.x,targetArrival.y,8,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#e8c7ff";ctx.font="8px ui-monospace,monospace";ctx.fillText(`${nav.route.targetName.toUpperCase()} NA CHEGADA`,targetArrival.x+11,targetArrival.y+4)}const t=clamp(progress??nav.progress/100),sample=samples[Math.min(samples.length-1,Math.round(t*(samples.length-1)))];if(sample&&Math.hypot(sample.x,sample.y)<=view.maxAu*1.12){const p=project(sample),next=project(samples[Math.min(samples.length-1,Math.round(t*(samples.length-1))+1)]||sample),angle=Math.atan2(next.y-p.y,next.x-p.x);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(angle);ctx.fillStyle="#fff";ctx.shadowColor="#55e9ff";ctx.shadowBlur=18;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-8,-6);ctx.lineTo(-4,0);ctx.lineTo(-8,6);ctx.closePath();ctx.fill();ctx.restore();ctx.shadowBlur=0;ctx.fillStyle="#8de9f8";ctx.font="700 9px ui-monospace,monospace";ctx.fillText(`ARK-01 ${Math.round(t*100)}%`,p.x+12,p.y+15)}}layoutCache.set(canvas,screenPoints);return true;
}

export function bindNavigationMap(canvas,onSelect){if(!canvas||canvas.dataset.navBound)return;canvas.dataset.navBound="1";const select=event=>{const rect=canvas.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,points=layoutCache.get(canvas)||[],nearest=points.map(point=>({...point,distance:Math.hypot(point.x-x,point.y-y)})).sort((a,b)=>a.distance-b.distance)[0];if(nearest&&nearest.distance<=22&&nearest.id!=="earth")onSelect?.(nearest.id)};canvas.addEventListener("pointerup",select);canvas.addEventListener("keydown",event=>{if(event.key!=="Enter"&&event.key!==" ")return;const points=layoutCache.get(canvas)||[],target=points.find(point=>point.id!=="earth");if(target){event.preventDefault();onSelect?.(target.id)}})}

export {mapViews};
