import {planetaryPositions,missionDate} from "../sim/solar-system.js";
import {ensureNavigationState} from "../sim/interplanetary.js";

const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,value));
const safe=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));

export function navigationPlannerView(state,solarData){
  const nav=ensureNavigationState(state),route=nav.route,bodies=solarData.bodies.filter(body=>body.id!=="earth");
  return `<section class="navigation-planner"><header><div><div class="eyebrow">COMPUTADOR DE ROTA · EFEMÉRIDES JPL</div><h2>Destino obrigatório da missão</h2><p>Escolha livremente um planeta. Jun calcula distância, janela e energia; a decisão final é do comandante.</p></div><span class="chip ${nav.locked?"":"warn"}">${nav.locked?"ROTA TRAVADA":"ROTA NÃO CONFIRMADA"}</span></header><div class="navigation-layout"><div class="navigation-map-wrap"><canvas id="navigation-map" aria-label="Mapa GPS interplanetário com a posição da ARK-01"></canvas><div class="navigation-map-hud"><span>GPS HELIOCÊNTRICO · J2000</span><b>${route?safe(route.targetName):"SELECIONE UM ALVO"}</b><small data-nav-progress>ARK-01 · ${Math.round(nav.progress||0)}%</small></div></div><aside><div class="nav-targets">${bodies.map(body=>`<button class="${nav.selectedBody===body.id?"selected":""}" data-nav-target="${body.id}"><i style="--body:${body.color}"></i><span>${safe(body.name)}</span><small>${safe(body.description)}</small></button>`).join("")}</div>${route?`<div class="nav-route-card"><div class="nav-route-metrics"><span>DISTÂNCIA<b>${route.separationAu.toFixed(3)} UA</b></span><span>TRANSFERÊNCIA<b>${route.transferDays.toFixed(0)} dias</b></span><span>ΔV PARTIDA<b>${route.departureDvMps.toFixed(0)} m/s</b></span><span>JANELA<b>${route.windowQuality}%</b></span><span>VEL. MÉDIA<b>${route.cruiseSpeedKmS.toFixed(1)} km/s</b></span><span>HABITABILIDADE<b>${route.suitability}%</b></span></div><div class="nav-advisor"><img src="./assets/images/avatars/jun-park.webp" alt="Jun Park"><p><b>JUN PARK · PILOTO</b><span>${safe(route.warning)} ${route.phaseErrorDeg>35?"A janela atual é ruim; podemos partir, mas o custo e o tempo aumentam.":"A geometria da janela é aceitável para planejamento."}</span></p></div><button class="primary" data-nav-lock ${nav.locked?"disabled":""}>${nav.locked?"ROTA CONFIRMADA":"CONFIRMAR E GRAVAR ROTA"}</button></div>`:`<div class="nav-empty"><b>Nenhuma rota traçada</b><span>O nó de partida permanecerá bloqueado até você escolher e confirmar um planeta.</span></div>`}</aside></div></section>`;
}

export function drawNavigationMap(canvas,state,solarData,{progress}={}){
  if(!canvas)return false;const ctx=canvas.getContext("2d");if(!ctx)return false;const rect=canvas.getBoundingClientRect(),dpr=Math.min(globalThis.devicePixelRatio||1,2),w=Math.max(2,Math.round(rect.width*dpr)),h=Math.max(2,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);const W=w/dpr,H=h/dpr,cx=W*.5,cy=H*.5,maxR=Math.min(W,H)*.43,nav=ensureNavigationState(state),positions=planetaryPositions(missionDate(state),solarData),radial=au=>18+(maxR-18)*Math.log1p(au*4)/Math.log1p(30.1*4),point=body=>{const angle=Math.atan2(body.y,body.x),r=radial(body.distanceAu);return {x:cx+Math.cos(angle)*r,y:cy+Math.sin(angle)*r*.92}};
  const bg=ctx.createRadialGradient(cx,cy,0,cx,cy,maxR*1.5);bg.addColorStop(0,"#0b2537");bg.addColorStop(1,"#010305");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);for(let i=0;i<125;i++){ctx.fillStyle=`rgba(205,235,255,${.1+(i%7)*.04})`;ctx.fillRect((i*97)%W,(i*53)%H,1,1)}solarData.bodies.forEach(body=>{ctx.strokeStyle="rgba(75,151,184,.18)";ctx.beginPath();ctx.arc(cx,cy,radial(body.elements.a[0]),0,Math.PI*2);ctx.stroke()});ctx.fillStyle="#ffd25b";ctx.shadowColor="#ffb42a";ctx.shadowBlur=18;ctx.beginPath();ctx.arc(cx,cy,8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
  const points=new Map();positions.forEach(body=>{const p=point(body);points.set(body.id,p);ctx.fillStyle=body.color;ctx.shadowColor=body.color;ctx.shadowBlur=body.id===nav.selectedBody?14:4;ctx.beginPath();ctx.arc(p.x,p.y,body.id===nav.selectedBody?6:body.id==="earth"?5:3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;if(body.id==="earth"||body.id===nav.selectedBody){ctx.fillStyle="#d9f2f8";ctx.font="10px ui-monospace,monospace";ctx.fillText(body.name.toUpperCase(),p.x+8,p.y-7)}});
  if(nav.route&&points.has("earth")&&points.has(nav.route.targetId)){const a=points.get("earth"),b=points.get(nav.route.targetId),control={x:(a.x+b.x)/2+(cy-(a.y+b.y)/2)*.28,y:(a.y+b.y)/2-((cx-(a.x+b.x)/2)*.28)};ctx.setLineDash([6,5]);ctx.strokeStyle=nav.locked?"#ffbd58":"#6adff4";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(control.x,control.y,b.x,b.y);ctx.stroke();ctx.setLineDash([]);const t=clamp(progress??nav.progress/100),u=1-t,x=u*u*a.x+2*u*t*control.x+t*t*b.x,y=u*u*a.y+2*u*t*control.y+t*t*b.y,dx=2*u*(control.x-a.x)+2*t*(b.x-control.x),dy=2*u*(control.y-a.y)+2*t*(b.y-control.y),angle=Math.atan2(dy,dx);ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle="#fff";ctx.shadowColor="#62eeff";ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(-7,-5);ctx.lineTo(-3,0);ctx.lineTo(-7,5);ctx.closePath();ctx.fill();ctx.restore();ctx.shadowBlur=0;ctx.fillStyle="#8ddff0";ctx.font="9px ui-monospace,monospace";ctx.fillText(`ARK-01 ${Math.round(t*100)}%`,x+10,y+13)}return true;
}

