const vertex=`attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}`;
const fragment=`
precision highp float;
uniform vec2 resolution;
uniform float time,mode,progress;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}
float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<5;i++){v+=noise(p)*a;p=p*2.02+vec2(7.1,13.7);a*=.5;}return v;}
float terrain(vec2 p){float broad=fbm(p*.12)*2.1+fbm(p*.42)*.52;float ridges=abs(fbm(p*.22+5.)-.5)*1.3;return broad+(mode>.5&&mode<1.5?ridges:0.)+(mode>1.5?fbm(p*.85)*.7:0.);}
float map(vec3 p){return p.y-terrain(p.xz);}
vec3 normalAt(vec3 p){float e=.025;return normalize(vec3(map(p+vec3(e,0,0))-map(p-vec3(e,0,0)),2.*e,map(p+vec3(0,0,e))-map(p-vec3(0,0,e))));}
vec3 palette(float h){vec3 boreal=mix(vec3(.035,.12,.16),vec3(.55,.72,.73),smoothstep(.7,2.4,h));vec3 delta=mix(vec3(.16,.09,.045),vec3(.65,.41,.20),smoothstep(.5,2.5,h));vec3 iris=mix(vec3(.08,.045,.11),vec3(.44,.23,.55),smoothstep(.4,2.3,h));return mode<.5?boreal:mode<1.5?delta:iris;}
void main(){
 vec2 uv=(gl_FragCoord.xy/resolution)*2.-1.;uv.x*=resolution.x/resolution.y;
 float travel=time*.025;vec3 ro=vec3(sin(time*.015)*1.2,3.1+progress*.4,-6.+travel),target=vec3(0.,1.05,3.+travel);vec3 fw=normalize(target-ro),rt=normalize(cross(fw,vec3(0,1,0))),up=cross(rt,fw),rd=normalize(fw+uv.x*rt*.75+uv.y*up*.75);
 vec3 sun=normalize(vec3(-.55,.62,-.35));float sunDisc=pow(max(dot(rd,sun),0.),850.);vec3 sky=mix(mode<.5?vec3(.018,.055,.09):mode<1.5?vec3(.15,.065,.035):vec3(.06,.025,.09),vec3(.015,.025,.045),max(rd.y,0.));sky+=vec3(1.,.58,.25)*sunDisc*3.;
 float t=0.,hit=0.;vec3 p=ro;for(int i=0;i<96;i++){p=ro+rd*t;float d=map(p);if(abs(d)<.012){hit=1.;break;}t+=max(.018,d*.38);if(t>55.)break;}
 vec3 color=sky;if(hit>.5){vec3 n=normalAt(p);float diff=max(dot(n,sun),0.),shadow=.35+.65*diff,h=terrain(p.xz),detail=noise(p.xz*8.);vec3 ground=palette(h)*shadow*(.76+detail*.24);float ice=mode<.5?smoothstep(1.5,2.45,h)*(.65+.35*detail):0.;ground=mix(ground,vec3(.72,.84,.86),ice);float mineral=mode>1.5?step(.84,noise(p.xz*2.7))*smoothstep(.2,.8,diff):0.;ground+=vec3(.24,.08,.32)*mineral;float fog=1.-exp(-t*(mode<.5?.045:.025));color=mix(ground,sky,fog);}
 float stars=step(.998,hash(floor(uv*vec2(650.,360.))))*smoothstep(.15,.85,uv.y);color+=stars*vec3(.6,.82,1.);color=vec3(1.)-exp(-color*1.45);gl_FragColor=vec4(pow(color,vec3(.88)),1.);
}`;
function compile(gl,type,source){const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(shader));return shader}
function createProgram(gl){let pixel=fragment;let program;for(let attempt=0;attempt<2;attempt++){program=gl.createProgram();try{gl.attachShader(program,compile(gl,gl.VERTEX_SHADER,vertex));gl.attachShader(program,compile(gl,gl.FRAGMENT_SHADER,pixel));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));return program}catch(error){if(attempt)throw error;pixel=fragment.replace("precision highp float","precision mediump float")}}}
export function createPlanetSurfaceRenderer(canvas,{site="boreal",reduceMotion=false}={}){const gl=canvas?.getContext("webgl",{antialias:false,powerPreference:"high-performance"});if(!gl)return null;try{const program=createProgram(gl),buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);gl.useProgram(program);const position=gl.getAttribLocation(program,"p");gl.enableVertexAttribArray(position);gl.vertexAttribPointer(position,2,gl.FLOAT,false,0,0);const start=performance.now(),modes={boreal:0,delta:1,iris:2},mobile=globalThis.matchMedia?.("(max-width: 720px)")?.matches??false,resize=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,mobile?.82:1.35),w=Math.max(2,Math.round(rect.width*dpr)),h=Math.max(2,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);return {w,h}},render=()=>{const {w,h}=resize(),now=reduceMotion?0:(performance.now()-start)/1000;gl.useProgram(program);gl.uniform2f(gl.getUniformLocation(program,"resolution"),w,h);gl.uniform1f(gl.getUniformLocation(program,"time"),now);gl.uniform1f(gl.getUniformLocation(program,"mode"),modes[site]??1);gl.uniform1f(gl.getUniformLocation(program,"progress"),0);gl.drawArrays(gl.TRIANGLES,0,6)};let frame,last=0;const loop=stamp=>{if(!mobile||stamp-last>=33){render();last=stamp}frame=requestAnimationFrame(loop)};if(reduceMotion)render();else frame=requestAnimationFrame(loop);return {destroy(){if(frame)cancelAnimationFrame(frame);gl.deleteProgram(program);gl.deleteBuffer(buffer)}}}catch{return null}}
