import {rendezvousTelemetry,stepRendezvous} from "../sim/rendezvous.js";

const fmt=(value,digits=1)=>Number(value).toFixed(digits);

export function rendezvousView(state,{portrait}){
  const rv=state.mission.rendezvous,telemetry=rendezvousTelemetry(rv),finished=["docked","collision","aborted"].includes(rv.status);
  return `<section class="rv-simulator ${finished?`result-${rv.status}`:""}">
    <header class="rv-command"><div><div class="eyebrow">SIMULADOR RVD · DINÂMICA RELATIVA CLOHESSY–WILTSHIRE</div><h1>Aproximação e acoplagem orbital</h1><p>Controle translação e atitude no referencial LVLH. O alvo continua orbitando a Terra: parar no espaço não significa parar em relação ao porto.</p></div><div class="rv-mode"><span>ALVO</span><b>${rv.target}</b><small>${rv.assistance==="sas"?"SAS DE ATITUDE ATIVO":"CONTROLE DIRETO"}</small></div></header>
    <div class="rv-layout"><section class="rv-window"><canvas id="rendezvous-canvas" aria-label="Visão da janela de acoplagem"></canvas><div class="rv-window-label"><span>CAM-DOCK 01 · LVLH</span><b data-rv-annunciator>${finished?rv.status.toUpperCase():"APROXIMAÇÃO"}</b></div><div class="rv-reticle"><i></i><span>VETOR DE FECHAMENTO</span></div>${finished?resultOverlay(rv):""}</section>
    <aside class="rv-instruments"><div class="rv-primary"><div><span>DISTÂNCIA</span><b data-rv-range>${fmt(telemetry.rangeM)} m</b></div><div><span>FECHAMENTO</span><b data-rv-closing>${fmt(telemetry.closingRateMps,2)} m/s</b></div></div><div class="rv-grid"><div><span>VEL. REL.</span><b data-rv-speed>${fmt(telemetry.relativeSpeedMps,2)} m/s</b></div><div><span>DESVIO LATERAL</span><b data-rv-lateral>${fmt(telemetry.lateralM)} m</b></div><div><span>CORREDOR</span><b data-rv-corridor>${fmt(telemetry.corridorDeg,2)}°</b></div><div><span>ATITUDE</span><b data-rv-attitude>${fmt(telemetry.attitudeErrorDeg,2)}°</b></div><div><span>RCS</span><b data-rv-fuel>${fmt(telemetry.propellantPct,0)}%</b></div><div><span>MET</span><b data-rv-time>${fmt(rv.elapsedSeconds,0)} s</b></div></div><div class="rv-bars"><label>CORREDOR <i data-rv-corridor-bar style="--value:${Math.min(100,telemetry.corridorDeg*10)}%"></i></label><label>VELOCIDADE <i data-rv-speed-bar style="--value:${Math.min(100,telemetry.relativeSpeedMps*130)}%"></i></label></div>
    <section class="rv-advisor">${portrait("jun-park")}<div><span>JUN PARK · PILOTO</span><b data-rv-guidance>${guidance(telemetry)}</b><small>Contato seguro: velocidade ≤ 0,14 m/s, desvio ≤ 0,32 m e atitude ≤ 5,5°.</small></div></section>
    ${finished?`<button class="primary" data-rv-reset>NOVA APROXIMAÇÃO</button><button data-route="operations">VOLTAR ÀS OPERAÇÕES</button>`:controlsPanel()}</aside></div>
    <footer class="rv-science"><span>MODELO</span><b>Hill/Clohessy–Wiltshire · órbita terrestre a 220 km</b><span>FORÇAS</span><b>gravidade diferencial, Coriolis, RCS, deriva de atitude</b><span>SAVE</span><b>resultado e dano persistentes</b></footer>
  </section>`;
}

function controlsPanel(){return `<section class="rv-controls"><div class="rv-assist"><button data-rv-auto class="active">AUTO-APROXIMAÇÃO</button><button data-rv-warp>ACELERAÇÃO 1×</button></div><div class="rv-pad rv-translate"><span>TRANSLAÇÃO</span><button data-rv-control="up">R<br><small>SUBIR</small></button><button data-rv-control="left">A<br><small>ESQ.</small></button><button data-rv-control="forward">W<br><small>FRENTE</small></button><button data-rv-control="right">D<br><small>DIR.</small></button><button data-rv-control="down">F<br><small>DESCER</small></button><button data-rv-control="back">S<br><small>RÉ</small></button></div><div class="rv-pad rv-rotate"><span>ATITUDE</span><button data-rv-control="pitchUp">↑<small>PITCH</small></button><button data-rv-control="yawLeft">←<small>YAW</small></button><button data-rv-control="rollLeft">Q<small>ROLL</small></button><button data-rv-control="yawRight">→<small>YAW</small></button><button data-rv-control="pitchDown">↓<small>PITCH</small></button><button data-rv-control="rollRight">E<small>ROLL</small></button></div></section>`}
function resultOverlay(rv){const success=rv.status==="docked";return `<div class="rv-result"><span>${success?"CAPTURA CONFIRMADA":rv.status==="collision"?"IMPACTO NO PORTO":"APROXIMAÇÃO ABORTADA"}</span><b>${success?"ACOPLAGEM NOMINAL":rv.status==="collision"?"COLISÃO ORBITAL":"JANELA ENCERRADA"}</b><small>${success?"Garras estruturais travadas e vedação em curso.":"O resultado foi registrado; casco, confiança e missão receberam consequências."}</small></div>`}
function guidance(t){if(t.rangeM<12&&t.relativeSpeedMps>.18)return"FREIE. Taxa de fechamento acima do corredor.";if(t.lateralM>Math.max(.3,t.rangeM*.08))return"Corrija o desvio lateral antes de continuar fechando.";if(t.attitudeErrorDeg>5)return"Alinhe a cruz de atitude com o eixo do porto.";if(t.closingRateMps<.02)return"Aplique pulso à frente e monitore a deriva orbital.";return"Corredor estável. Faça pulsos pequenos; não persiga o retículo."}

const keyMap={KeyW:"forward",KeyS:"back",KeyA:"left",KeyD:"right",KeyR:"up",KeyF:"down",ArrowUp:"pitchUp",ArrowDown:"pitchDown",ArrowLeft:"yawLeft",ArrowRight:"yawRight",KeyQ:"rollLeft",KeyE:"rollRight"};
const controlsFrom=held=>({forward:(held.has("forward")?1:0)-(held.has("back")?1:0),right:(held.has("right")?1:0)-(held.has("left")?1:0),up:(held.has("up")?1:0)-(held.has("down")?1:0),pitch:(held.has("pitchUp")?1:0)-(held.has("pitchDown")?1:0),yaw:(held.has("yawRight")?1:0)-(held.has("yawLeft")?1:0),roll:(held.has("rollRight")?1:0)-(held.has("rollLeft")?1:0),sas:true});
function autopilot(rv){const t=rendezvousTelemetry(rv),desired=t.rangeM>60?.38:t.rangeM>20?.24:t.rangeM>6?.11:.055,desiredVx=-desired;return {forward:Math.max(-1,Math.min(1,(rv.vx-desiredVx)*7)),right:Math.max(-1,Math.min(1,-rv.y*.045-rv.vy*2.4)),up:Math.max(-1,Math.min(1,-rv.z*.045-rv.vz*2.4)),pitch:0,yaw:0,roll:0,sas:true}}

export function createRendezvousController({root,canvas,initial,onComplete,onMilestone,reduceMotion=false}){
  if(!root||!canvas||["docked","collision","aborted"].includes(initial.status))return null;
  const rv=structuredClone(initial),ctx=canvas.getContext("2d"),held=new Set();let frame,last=performance.now(),auto=true,warp=1,done=false,closeCalled=false;
  const down=event=>{const name=event.currentTarget?.dataset?.rvControl||keyMap[event.code];if(name){event.preventDefault();held.add(name);event.currentTarget?.classList.add("pressed")}},up=event=>{const name=event.currentTarget?.dataset?.rvControl||keyMap[event.code];if(name){held.delete(name);event.currentTarget?.classList.remove("pressed")}};
  addEventListener("keydown",down);addEventListener("keyup",up);root.querySelectorAll("[data-rv-control]").forEach(button=>{button.addEventListener("pointerdown",down);button.addEventListener("pointerup",up);button.addEventListener("pointercancel",up);button.addEventListener("pointerleave",up)});
  root.querySelector("[data-rv-auto]")?.addEventListener("click",event=>{auto=!auto;event.currentTarget.classList.toggle("active",auto);event.currentTarget.textContent=auto?"AUTO-APROXIMAÇÃO":"CONTROLE MANUAL"});
  root.querySelector("[data-rv-warp]")?.addEventListener("click",event=>{warp=warp===1?4:warp===4?10:1;event.currentTarget.textContent=`ACELERAÇÃO ${warp}×`});
  const set=(selector,text)=>{const el=root.querySelector(selector);if(el)el.textContent=text},bar=(selector,value)=>root.querySelector(selector)?.style.setProperty("--value",`${Math.min(100,value)}%`);
  const update=t=>{set("[data-rv-range]",`${fmt(t.rangeM)} m`);set("[data-rv-closing]",`${fmt(t.closingRateMps,2)} m/s`);set("[data-rv-speed]",`${fmt(t.relativeSpeedMps,2)} m/s`);set("[data-rv-lateral]",`${fmt(t.lateralM)} m`);set("[data-rv-corridor]",`${fmt(t.corridorDeg,2)}°`);set("[data-rv-attitude]",`${fmt(t.attitudeErrorDeg,2)}°`);set("[data-rv-fuel]",`${fmt(t.propellantPct,0)}%`);set("[data-rv-time]",`${fmt(rv.elapsedSeconds,0)} s`);set("[data-rv-guidance]",guidance(t));bar("[data-rv-corridor-bar]",t.corridorDeg*10);bar("[data-rv-speed-bar]",t.relativeSpeedMps*130)};
  const loop=now=>{const elapsed=Math.min(.1,(now-last)/1000);last=now;const t0=rendezvousTelemetry(rv);if(t0.rangeM<18&&warp>1){warp=1;const button=root.querySelector("[data-rv-warp]");if(button)button.textContent="ACELERAÇÃO 1×"}const steps=Math.max(1,Math.round(warp));let t=t0;for(let i=0;i<steps;i++)t=stepRendezvous(rv,auto?autopilot(rv):controlsFrom(held),elapsed);if(t.rangeM<20&&!closeCalled){closeCalled=true;onMilestone?.("close",structuredClone(rv))}draw(ctx,canvas,rv,t,reduceMotion?0:now/1000);update(t);if(["docked","collision","aborted"].includes(rv.status)&&!done){done=true;onComplete?.(structuredClone(rv));return}frame=requestAnimationFrame(loop)};
  frame=requestAnimationFrame(loop);return {destroy(){cancelAnimationFrame(frame);removeEventListener("keydown",down);removeEventListener("keyup",up)},snapshot:()=>structuredClone(rv)};
}

function draw(ctx,canvas,rv,t,time){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5),w=Math.max(2,Math.round(rect.width*dpr)),h=Math.max(2,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}ctx.setTransform(dpr,0,0,dpr,0,0);const W=rect.width,H=rect.height,g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#01040a");g.addColorStop(.68,"#020811");g.addColorStop(1,"#0b2231");ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle="#9bdcff";for(let i=0;i<85;i++){const x=(i*137.3%W),y=(i*71.9%Math.max(1,H*.72)),a=.18+(i%7)/16;ctx.globalAlpha=a;ctx.fillRect(x,y,i%9===0?1.5:.7,i%9===0?1.5:.7)}ctx.globalAlpha=1;ctx.beginPath();ctx.ellipse(W*.5,H*1.32,W*.75,H*.66,0,Math.PI,Math.PI*2);ctx.fillStyle="#0a293c";ctx.fill();ctx.strokeStyle="#58cfff55";ctx.lineWidth=4;ctx.stroke();const scale=Math.min(W,H)*42/Math.max(18,t.rangeM),cx=W*.5-rv.y/Math.max(8,t.rangeM)*W*1.4,cy=H*.5+rv.z/Math.max(8,t.rangeM)*H*1.4,pulse=1+Math.sin(time*2)*.006,radius=Math.max(18,Math.min(Math.min(W,H)*.3,scale))*pulse;ctx.save();ctx.translate(cx,cy);ctx.rotate(rv.roll*Math.PI/180);ctx.fillStyle="#1b252c";ctx.strokeStyle="#8ba2ad";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,radius,0,Math.PI*2);ctx.fill();ctx.stroke();for(let i=0;i<12;i++){ctx.rotate(Math.PI/6);ctx.fillStyle=i%2?"#344854":"#253740";ctx.fillRect(radius*.72,-radius*.07,radius*.42,radius*.14)}ctx.fillStyle="#020608";ctx.strokeStyle="#62e2ff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,radius*.52,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle="#ffbd5b";ctx.beginPath();ctx.moveTo(-radius*.33,0);ctx.lineTo(radius*.33,0);ctx.moveTo(0,-radius*.33);ctx.lineTo(0,radius*.33);ctx.stroke();ctx.restore();ctx.strokeStyle=t.relativeSpeedMps>.18&&t.rangeM<20?"#ff665d":"#6ff0ff";ctx.lineWidth=1;ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(W*.5,H*.5);ctx.lineTo(cx,cy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#79eaff";ctx.font="11px monospace";ctx.fillText(`RNG ${t.rangeM.toFixed(1)} m`,18,H-30);ctx.fillText(`VREL ${t.relativeSpeedMps.toFixed(2)} m/s`,18,H-15)}
