export function createFlightAudio(volume=.56){
  if(volume<=0)return {start(){},update(){},cue(){},stop(){}};
  let context=null,master=null,rumble=null,rumbleGain=null,noise=null,noiseGain=null,filter=null,started=false;
  const init=()=>{if(context)return context;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return null;context=new AudioContext();master=context.createGain();master.gain.value=.32*Math.max(0,Math.min(1,volume));master.connect(context.destination);rumble=context.createOscillator();rumble.type="sawtooth";rumble.frequency.value=38;rumbleGain=context.createGain();rumbleGain.gain.value=.0001;rumble.connect(rumbleGain).connect(master);const buffer=context.createBuffer(1,context.sampleRate*2,context.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;noise=context.createBufferSource();noise.buffer=buffer;noise.loop=true;filter=context.createBiquadFilter();filter.type="lowpass";filter.frequency.value=420;noiseGain=context.createGain();noiseGain.gain.value=.0001;noise.connect(filter).connect(noiseGain).connect(master);rumble.start();noise.start();started=true;return context};
  const ramp=(node,value,time=.12)=>{if(!context||!node)return;node.cancelScheduledValues(context.currentTime);node.linearRampToValueAtTime(value,context.currentTime+time)};
  return {
    async start(){const ctx=init();if(ctx?.state==="suspended")await ctx.resume()},
    update(telemetry,flight){if(!started||!context)return;const thrust=Math.min(1,(telemetry.thrustN||0)/8200000),air=Math.min(1,(telemetry.dynamicPressurePa||0)/65000),active=flight.status==="ascent"&&!flight.paused;ramp(rumbleGain.gain,active ? .025+.085*thrust : .0001);ramp(noiseGain.gain,active ? .012+.05*air : .0001);ramp(rumble.frequency,31+thrust*28,.18);ramp(filter.frequency,180+thrust*520+air*900,.18)},
    cue(type="radio"){const ctx=init();if(!ctx)return;if(ctx.state==="suspended")ctx.resume();const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type=type==="alarm"?"square":"sine";oscillator.frequency.setValueAtTime(type==="alarm"?210:780,ctx.currentTime);if(type==="radio")oscillator.frequency.exponentialRampToValueAtTime(1120,ctx.currentTime+.11);gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(type==="alarm"?.09:.045,ctx.currentTime+.015);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+(type==="alarm"?.45:.19));oscillator.connect(gain).connect(master||ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+(type==="alarm"?.48:.22))},
    stop(){if(!context)return;try{rumble?.stop();noise?.stop();context.close()}catch{}context=null;started=false}
  }
}
