import {tickDetailedSystems,detailedSystemsSnapshot} from "./ship-systems.js";

const clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,value));
const hash=text=>{let h=2166136261;for(const char of String(text)){h^=char.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const incidents=[
  {id:"reactor-ghost",speaker:"elias-brandt",role:"ENGENHEIRO DE BORDO",title:"O fantasma do reator",message:"O barramento B registra pulsos sem carga correspondente. Pode ser sensor, isolamento ou início de arco elétrico.",choices:[{id:"isolate",label:"Isolar o barramento B",detail:"Protege a nave, reduz redundância e atrasa a vigília.",safety:20,effects:{trust:2,morale:-1,backlog:1},impact:"SEGURANÇA ALTA · REDUNDÂNCIA MENOR"},{id:"inspect",label:"Inspeção física imediata",detail:"Elias entra no compartimento energizado para localizar a origem.",safety:8,skill:"engineering",effects:{trust:4,science:2},impact:"RISCO HUMANO · DIAGNÓSTICO COMPLETO"},{id:"monitor",label:"Manter carga e observar",detail:"Preserva a missão, aceitando que o próximo pulso pode causar dano.",safety:-8,effects:{support:1},impact:"SEM ATRASO · RISCO DE CASCATA"}]},
  {id:"silent-crew",speaker:"samira-haddad",role:"FATORES HUMANOS",title:"Quarenta horas de silêncio",message:"Dois turnos deixaram de trocar relatórios e começaram a esconder erros pequenos. A eficiência subiu; a confiança caiu.",choices:[{id:"council",label:"Conselho obrigatório",detail:"Interromper operações e expor o conflito diante da tripulação.",safety:14,skill:"command",effects:{trust:5,morale:2},impact:"+CONFIANÇA · −TEMPO"},{id:"rotate",label:"Separar os turnos",detail:"Evita confronto imediato, mas transforma tensão em procedimento permanente.",safety:5,effects:{morale:1,cohesion:-2},impact:"ESTABILIDADE CURTA · COESÃO MENOR"},{id:"delegate",label:"Dar autonomia a Samira",detail:"A capitã não interfere; fatores humanos assumem a resolução.",safety:10,skill:"medical",effects:{trust:3,cohesion:3},impact:"AUTONOMIA DA EQUIPE"}]},
  {id:"course-bias",speaker:"jun-park",role:"PILOTO · NAVEGAÇÃO",title:"A rota não fecha",message:"A posição estimada diverge das estrelas de referência. Corrigir agora custa propelente; esperar aumenta a incerteza.",choices:[{id:"burn",label:"Correção imediata",detail:"Consumir reserva para voltar ao corredor nominal.",safety:18,effects:{fuel:-210,trust:2},impact:"−210 KG · ROTA PROTEGIDA"},{id:"calibrate",label:"Recalibrar antes da queima",detail:"Ganhar evidência e aceitar mais deriva durante seis horas.",safety:10,skill:"flight",effects:{science:3,drift:-8},impact:"DIAGNÓSTICO · JANELA MENOR"},{id:"coast",label:"Manter costeio",detail:"Confiar no modelo e preservar propelente para uma correção futura maior.",safety:-6,effects:{drift:12},impact:"POUPA COMBUSTÍVEL · INCERTEZA"}]},
  {id:"water-vote",speaker:"asha-rao",role:"MÉDICA DA MISSÃO",title:"Água para quem ainda não acordou",message:"A reciclagem perdeu rendimento. A reserva cobre a tripulação ativa ou os colonos em hibernação, não ambos na mesma margem.",choices:[{id:"repair",label:"Racionar e reparar",detail:"Toda a tripulação trabalha sob limite até a membrana ser reconstruída.",safety:14,skill:"engineering",effects:{morale:-3,water:3,trust:3},impact:"REPARO · FADIGA COLETIVA"},{id:"crew",label:"Priorizar tripulação ativa",detail:"Protege quem mantém a nave e reduz a reserva colonial.",safety:7,effects:{morale:2,support:-4,water:-2},impact:"SAÚDE AGORA · FUTURO MENOR"},{id:"sleepers",label:"Preservar hibernação",detail:"A equipe aceita racionamento severo para proteger os passageiros.",safety:9,effects:{morale:-5,support:6,trust:2},impact:"LEGITIMIDADE · MORAL MENOR"}]},
  {id:"unknown-signal",speaker:"malik-okoye",role:"ASTROBIOLOGIA",title:"Uma resposta antes da pergunta",message:"Uma portadora coerente mudou de frequência exatamente quando a ARK-01 iniciou sua observação.",choices:[{id:"listen",label:"Somente escutar",detail:"Preservar silêncio e coletar evidência por uma vigília completa.",safety:18,effects:{science:6},impact:"PRUDÊNCIA · +CIÊNCIA"},{id:"reply",label:"Responder com matemática",detail:"Transmitir constantes universais sem revelar arquivos humanos.",safety:2,skill:"science",effects:{science:10,support:2},impact:"PRIMEIRO CONTATO POSSÍVEL"},{id:"blackout",label:"Cortar transmissões",detail:"Proteger posição e tripulação, sacrificando dados e confiança científica.",safety:12,effects:{science:-3,trust:-2},impact:"SEGURANÇA · PERDA CIENTÍFICA"}]},
  {id:"shield-scar",speaker:"rafael-costa",role:"ENGENHARIA ESTRUTURAL",title:"A cicatriz no escudo",message:"Um impacto atravessou a primeira camada Whipple. A cabine está segura, mas o próximo fragmento encontrará menos material.",choices:[{id:"eva",label:"EVA de reparo",detail:"Restaurar blindagem com exposição direta da equipe.",safety:9,skill:"engineering",effects:{integrity:5,spares:-2},impact:"+CASCO · −2 PEÇAS"},{id:"rotate",label:"Girar a nave",detail:"Colocar a seção intacta no vetor de risco e alterar o balanço térmico.",safety:15,effects:{thermal:-6},impact:"SEM EVA · CARGA TÉRMICA"},{id:"accept",label:"Aceitar o dano",detail:"Preservar recursos e registrar uma vulnerabilidade permanente.",safety:-10,effects:{integrity:-4,backlog:2},impact:"POUPA RECURSOS · RISCO FUTURO"}]},
  {id:"earth-order",speaker:"amara-diallo",role:"COMANDANTE DA MISSÃO",title:"Uma ordem com atraso",message:"A Terra exige mudança de prioridade. A mensagem partiu antes da nossa última emergência e não conhece o estado atual da nave.",choices:[{id:"obey",label:"Cumprir a ordem",detail:"Preservar mandato político mesmo que o contexto já tenha mudado.",safety:4,effects:{support:7,trust:-4},impact:"+APOIO · −AUTONOMIA"},{id:"adapt",label:"Adaptar a intenção",detail:"Executar apenas o objetivo compatível com a situação presente.",safety:13,skill:"command",effects:{support:3,trust:3},impact:"EQUILÍBRIO · RESPONSABILIDADE"},{id:"refuse",label:"Recusar e registrar",detail:"A capitã assume publicamente que a Terra não pode comandar o presente.",safety:9,effects:{support:-6,trust:7,cohesion:3},impact:"AUTONOMIA · CUSTO POLÍTICO"}]},
  {id:"sleep-anomaly",speaker:"lena-volkov",role:"OPERAÇÕES DE HABITAT",title:"Alguém acordou cedo",message:"Uma cápsula de hibernação abriu sem comando. O passageiro está estável, mas não pode voltar ao sono sem risco neurológico.",choices:[{id:"integrate",label:"Integrar à tripulação",detail:"Ganhar uma pessoa ativa e consumir suporte não planejado.",safety:11,effects:{morale:4,water:-2,cohesion:-1},impact:"+MORAL · +CONSUMO"},{id:"resleep",label:"Tentar nova indução",detail:"Proteger recursos aceitando risco médico individual.",safety:-4,skill:"medical",effects:{trust:-2},impact:"RISCO MÉDICO · RECURSOS PRESERVADOS"},{id:"wake-team",label:"Acordar equipe de suporte",detail:"Dividir carga humana e multiplicar o consumo de longo prazo.",safety:16,effects:{morale:2,water:-4,trust:2},impact:"SEGURANÇA HUMANA · −RECURSOS"}]}
];

export function createDeepSpaceState(){return {version:1,cycle:0,current:null,history:[],lastOutcome:null,threat:12,factions:{earth:50,crew:55,science:50,civilian:50},doctrine:[]}}
export function ensureDeepSpaceState(state){state.mission||={};state.mission.deepSpace||=createDeepSpaceState();const deep=state.mission.deepSpace,base=createDeepSpaceState();for(const [key,value] of Object.entries(base))if(deep[key]===undefined)deep[key]=structuredClone(value);deep.history||=[];deep.factions={...base.factions,...(deep.factions||{})};return deep}
const skillFor=(state,skill)=>{const id=state.crew?.assignments?.[skill],fatigue=state.crew?.fatigue?.[id]||0;return clamp(55+(state.crew?.cohesion||60)*.28-fatigue*.22,25,96)};
const apply=(state,effects={},success=true)=>{const scale=success?1:.45;state.crew.morale=clamp(state.crew.morale+(effects.morale||0)*scale);state.crew.trust=clamp(state.crew.trust+(effects.trust||0)*scale);state.crew.cohesion=clamp(state.crew.cohesion+(effects.cohesion||0)*scale);state.agency.support=clamp(state.agency.support+(effects.support||0)*scale);state.science.points=Math.max(0,state.science.points+Math.round((effects.science||0)*scale));state.ship.integrity=clamp(state.ship.integrity+(effects.integrity||0)*scale);state.mission.orbit.propellantKg=Math.max(0,state.mission.orbit.propellantKg+(effects.fuel||0)*scale);const systems=state.mission.systemsModel;if(systems){systems.lifeSupport.waterPct=clamp(systems.lifeSupport.waterPct+(effects.water||0)*scale);systems.navigation.driftKm=Math.max(0,systems.navigation.driftKm+(effects.drift||0)*scale);systems.maintenance.spares=Math.max(0,systems.maintenance.spares+(effects.spares||0)*scale);systems.maintenance.backlog=Math.max(0,systems.maintenance.backlog+(effects.backlog||0)*scale);systems.thermal.coreC=clamp(systems.thermal.coreC-(effects.thermal||0)*scale,240,920)}};

export function openDeepSpaceIncident(state){const deep=ensureDeepSpaceState(state);if(deep.current)return deep.current;const last=deep.history.at(-1)?.incidentId,pool=incidents.filter(item=>item.id!==last),index=hash(`${state.meta?.seed}:${deep.cycle}:${state.time?.missionHours}`)%pool.length,template=pool[index],systems=detailedSystemsSnapshot(state),fatigue=Object.values(state.crew?.fatigue||{}),avg=fatigue.length?fatigue.reduce((a,b)=>a+b,0)/fatigue.length:0,severity=Math.round(clamp(18+deep.cycle*1.8+(100-state.ship.integrity)*.25+systems.warning*5+systems.critical*14+avg*.16,12,88));deep.current={...structuredClone(template),severity,openedAt:state.time.missionHours};deep.threat=clamp(deep.threat+severity*.08);return deep.current}

export function resolveDeepSpaceIncident(state,choiceId){const deep=ensureDeepSpaceState(state),incident=deep.current;if(!incident)return {ok:false,reason:"Nenhuma decisão de comando está aberta."};const choice=incident.choices.find(item=>item.id===choiceId);if(!choice)return {ok:false,reason:"Ordem desconhecida."};const skill=skillFor(state,choice.skill||"command"),chance=clamp(54+skill*.32+choice.safety-incident.severity*.38,8,96),roll=hash(`${state.meta.seed}:${incident.id}:${choice.id}:${deep.cycle}`)%100+1,success=roll<=chance;apply(state,choice.effects,success);if(!success){state.ship.integrity=clamp(state.ship.integrity-Math.max(1,Math.round(incident.severity/15)));state.crew.morale=clamp(state.crew.morale-3);ensureDetailedFailure(state,incident)}else{state.crew.trust=clamp(state.crew.trust+1);deep.threat=clamp(deep.threat-4)}const record={incidentId:incident.id,title:incident.title,choiceId:choice.id,choice:choice.label,impact:choice.impact,success,roll,chance:Math.round(chance),severity:incident.severity,speaker:incident.speaker,at:state.time.missionHours};deep.history.unshift(record);deep.history=deep.history.slice(0,60);deep.lastOutcome=record;deep.current=null;state.campaign.decisions.push({title:`Vigília ${deep.cycle}: ${incident.title}`,detail:`${choice.label}; ${success?"dentro da margem":"desvio operacional"}`});return {ok:true,incident,choice,record}}

function ensureDetailedFailure(state,incident){state.logs.failures.unshift({cause:incident.title,factors:["decisão de comando","degradação acumulada"],symptoms:["telemetria fora da margem","carga adicional da tripulação"],propagation:"Consequências incorporadas aos sistemas persistentes",detection:"Conselho da ponte ARK-01",mitigation:"Procedimento escolhido pelo capitão"});state.logs.failures=state.logs.failures.slice(0,30)}

export function advanceCruiseWatch(state){const deep=ensureDeepSpaceState(state);if(deep.current)return {ok:false,reason:"Resolva a decisão aberta antes de acelerar o tempo."};const nav=state.mission.navigation,route=nav?.route,transferDays=Math.max(30,route?.transferDays||365),progress=Number(nav?.progress??state.mission.route.progress??0),remainingDays=Math.max(1,transferDays*(1-progress/100)),days=Math.min(90,remainingDays),hours=days*24;state.time.missionHours+=hours;const nextProgress=clamp(progress+days/transferDays*100);state.mission.route.progress=nextProgress;if(nav)nav.progress=nextProgress;state.systems.propulsion.fuelPct=clamp(state.systems.propulsion.fuelPct-days*.012);state.systems.lifeSupport.foodDays=Math.max(0,state.systems.lifeSupport.foodDays-days);state.crew.morale=clamp(state.crew.morale-days*.018);state.crew.health.average=clamp(state.crew.health.average-days*.008);for(const [station,id] of Object.entries(state.crew.assignments||{}))if(id)state.crew.fatigue[id]=clamp((state.crew.fatigue[id]||0)+days*.035+(station==="engineering"?days*.012:0));tickDetailedSystems(state,hours,{stress:1+deep.threat/180});deep.cycle++;const arrived=nextProgress>=99.999;if(arrived){state.mission.route.progress=100;if(nav)nav.progress=100;state.campaign.flags.arrived=true;return {ok:true,days,arrived:true,incident:null,progress:100}}const incident=openDeepSpaceIncident(state);return {ok:true,days,arrived:false,incident,progress:nextProgress}}

export {incidents as deepSpaceIncidentTemplates};

