const clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,value));

export const orbitalCommandBriefs=[
  {id:"orbit-doctrine",stage:3,speaker:"amara-diallo",role:"COMANDANTE DA MISSÃO",title:"Quem controla o corredor orbital?",message:"A ARK-01 estabilizou a órbita, mas três blocos políticos exigem prioridade. Esta doutrina mudará risco, contratos e reputação nos ciclos seguintes.",choices:[
    {id:"independent",label:"Auditoria técnica independente",detail:"Suspender operações por algumas horas e abrir todas as margens à equipe de segurança.",effects:{budget:-2,support:4,trust:3,reputation:1},modifiers:{operationRisk:-4,readiness:4},impact:"−4 risco futuro · +4 prontidão · −2 bi"},
    {id:"open",label:"Corredor científico aberto",detail:"Compartilhar efemérides e aceitar missões civis internacionais sob coordenação GSEA.",effects:{support:8,political:-3,reputation:4},modifiers:{operationRisk:1,rewardBonus:1},impact:"+4 reputação · +8 apoio · risco +1"},
    {id:"classified",label:"Prioridade estratégica fechada",detail:"Reservar a órbita para contratos governamentais e ocultar capacidades sensíveis da ARK-01.",effects:{budget:5,support:-7,political:6,reputation:-2},modifiers:{operationRisk:3,rewardBonus:4},impact:"+5 bi · +4 recompensa · −7 apoio"}
  ]},
  {id:"reserve-policy",stage:4,speaker:"elias-brandt",role:"ENGENHARIA E LOGÍSTICA",title:"Como dividir a reserva orbital?",message:"Temos propelente para a partida, mas não para todas as contingências. A reserva escolhida definirá quais missões futuras continuam possíveis.",choices:[
    {id:"rescue",label:"Reserva humanitária",detail:"Separar propelente e kits para salvamentos, mesmo reduzindo a margem de exploração imediata.",effects:{propellant:-600,trust:5,reputation:3},modifiers:{operationRisk:-2,fuelMultiplier:.94},impact:"−600 kg agora · −6% consumo futuro · +3 reputação"},
    {id:"expedition",label:"Reserva integral da expedição",detail:"Preservar alcance máximo para o planeta escolhido e recusar desvios não essenciais.",effects:{support:-3,science:2},modifiers:{rewardBonus:3,reputationBonus:-1},impact:"+3 recompensa · +2 ciência · −3 apoio"},
    {id:"instruments",label:"Converter massa em observatórios",detail:"Trocar parte do propelente por sensores e autonomia científica de longa duração.",effects:{propellant:-350,science:8},modifiers:{operationRisk:-1,readiness:2},impact:"−350 kg · +8 ciência · +2 prontidão"}
  ]},
  {id:"crew-authority",stage:4,speaker:"samira-haddad",role:"FATORES HUMANOS",title:"Quem decide durante o silêncio de rádio?",message:"Atrasos de comunicação tornam impossível consultar a Terra em cada crise. Defina agora a cadeia de autoridade que governará as missões distantes.",choices:[
    {id:"captain",label:"Autonomia do capitão e conselho",detail:"O capitão decide após ouvir especialistas; a Terra recebe o relatório depois da execução.",effects:{trust:5,morale:3,cohesion:4,political:-3,reputation:2},modifiers:{operationRisk:-2,reputationBonus:2},impact:"+5 confiança · +4 coesão · −2 risco futuro"},
    {id:"earth",label:"Supervisão obrigatória da Terra",detail:"Aguardar autorização terrestre sempre que houver vidas, território ou primeiro contato em jogo.",effects:{political:7,trust:-4,support:2},modifiers:{readiness:-1,rewardBonus:2},impact:"+7 influência · −4 confiança · decisões mais lentas"},
    {id:"aura",label:"AURA recomenda, humanos confirmam",detail:"A inteligência de bordo calcula cenários, mas a assinatura final permanece humana e auditável.",effects:{reliability:4,science:3,morale:-2},modifiers:{operationRisk:-3,readiness:3},impact:"+4 confiabilidade · −3 risco · +3 ciência"}
  ]}
];

export function createOrbitalCommandState(){return {version:1,resolved:[],modifiers:{operationRisk:0,readiness:0,rewardBonus:0,reputationBonus:0,fuelMultiplier:1},lastDecision:null}}
export function ensureOrbitalCommandState(state){state.mission||={};state.mission.commandCouncil||=createOrbitalCommandState();const council=state.mission.commandCouncil,base=createOrbitalCommandState();for(const [key,value] of Object.entries(base))if(council[key]===undefined)council[key]=structuredClone(value);council.resolved||=[];council.modifiers={...base.modifiers,...(council.modifiers||{})};return council}
export function currentOrbitalBrief(state,stage){const council=ensureOrbitalCommandState(state),done=new Set(council.resolved.map(item=>item.briefId));return orbitalCommandBriefs.find(brief=>brief.stage<=stage&&!done.has(brief.id))||null}
export function orbitalCommandReady(state,stage){const council=ensureOrbitalCommandState(state),done=new Set(council.resolved.map(item=>item.briefId));return orbitalCommandBriefs.filter(brief=>brief.stage<=stage).every(brief=>done.has(brief.id))}

function applyEffects(state,effects={}){state.economy.available=Math.max(0,state.economy.available+(effects.budget||0));state.agency.support=clamp(state.agency.support+(effects.support||0));state.agency.politicalCapital=clamp(state.agency.politicalCapital+(effects.political||0));state.crew.trust=clamp(state.crew.trust+(effects.trust||0));state.crew.morale=clamp(state.crew.morale+(effects.morale||0));state.crew.cohesion=clamp(state.crew.cohesion+(effects.cohesion||0));state.ship.reliability=clamp((state.ship.reliability||70)+(effects.reliability||0));state.science.points=Math.max(0,state.science.points+(effects.science||0));state.mission.orbit.propellantKg=Math.max(0,state.mission.orbit.propellantKg+(effects.propellant||0));if(state.operations)state.operations.reputation=Math.max(0,(state.operations.reputation||0)+(effects.reputation||0))}

export function resolveOrbitalCommandDecision(state,briefId,choiceId){const council=ensureOrbitalCommandState(state),brief=orbitalCommandBriefs.find(item=>item.id===briefId),current=currentOrbitalBrief(state,state.mission.flightStage||3);if(!brief||current?.id!==brief.id)return {ok:false,reason:"Este parecer não é a decisão aberta no momento."};const choice=brief.choices.find(item=>item.id===choiceId);if(!choice)return {ok:false,reason:"Diretriz orbital desconhecida."};applyEffects(state,choice.effects);for(const [key,value] of Object.entries(choice.modifiers||{}))council.modifiers[key]=key==="fuelMultiplier"?council.modifiers[key]*value:council.modifiers[key]+value;const record={briefId:brief.id,title:brief.title,choiceId:choice.id,choice:choice.label,impact:choice.impact,speaker:brief.speaker,at:state.time.missionHours};council.resolved.push(record);council.lastDecision=record;state.campaign.decisions.push({title:`Conselho orbital: ${brief.title}`,detail:`${choice.label}; ${choice.impact}`});return {ok:true,brief,choice,record,modifiers:structuredClone(council.modifiers)}}
