import { createInitialState, createStore } from "./core/store.js";
import { createRouter } from "./ui/router.js";
import { recalculate, completeTest, simulateLaunch, advanceCruise, applyEventChoice, scanPlanet, buildColony, endingFor, clamp } from "./sim/simulation.js";
import { saveGame, loadGame, listSaves, deleteSave, exportGame, importGame } from "./data/save-manager.js";

const app=document.querySelector("#app"),toastRegion=document.querySelector("#toast-region");
const [data,locales,version]=await Promise.all(["game.json","locales.json"].map(n=>fetch(`./data/${n}`).then(r=>{if(!r.ok)throw new Error(`Falha ao carregar ${n}`);return r.json()})).concat(fetch("./version.json").then(r=>r.json())));
let locale=localStorage.getItem("lh-locale")||"pt-BR",lastState=null,autosaveTimer=null;
const t=key=>locales[locale]?.[key]||locales["pt-BR"][key]||key;
const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const pct=n=>`${Math.round(clamp(n))}%`,money=n=>`${Math.round(n)} bi`;
const initial=recalculate(createInitialState(),data);
const store=createStore(initial,s=>recalculate(s,data));

function toast(message,type="ok"){const el=document.createElement("div");el.className=`toast ${type}`;el.textContent=message;toastRegion.append(el);setTimeout(()=>el.remove(),3200)}
function audioCue(type="select"){
  if(!store.getState().profile.audio)return;
  try{const Ctx=window.AudioContext||window.webkitAudioContext,ctx=new Ctx(),o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.value=type==="alarm"?190:type==="success"?620:420;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.17)}catch{}
}
function applyAccessibility(state){const a=state.profile.accessibility;document.body.classList.toggle("reduce-motion",a.reduceMotion);document.body.classList.toggle("high-contrast",a.highContrast);document.body.classList.toggle("large-text",a.largeText);document.body.classList.toggle("colorblind",a.colorblind)}
function logTime(hours){const day=Math.floor(hours/24);return `D+${String(day).padStart(3,"0")}`}

function menu(){const s=store.getState(),hasSave=!!localStorage.getItem("lh-has-save");app.innerHTML=`
  <main class="splash"><section class="splash-content">
    <div class="eyebrow">GSEA · PROJECT HAVEN</div><h1><span>GLOBAL SPACE AGENCY SIMULATOR</span>LAST<br>HORIZON</h1>
    <p class="lead">A Terra está ficando sem tempo. Projete a ARK-01, lidere sua tripulação e decida quais riscos a humanidade carregará até outro mundo.</p>
    <div class="menu-buttons">
      <button class="primary" data-action="new">${t("new")}</button>
      <button data-action="continue" ${hasSave?"":"disabled"}>${t("continue")}</button>
      <button data-action="expedition">${t("expedition")}</button>
      <button data-action="simulator">${t("simulator")}</button>
      <button data-action="saves">${t("saves")}</button><button data-action="settings">${t("settings")}</button>
    </div><div class="build-tag">${t("build")} · ${esc(version.build)}</div>
  </section></main>`;
  bindMenu();
}

function bindMenu(){
  one("[data-action=new]","click",()=>profileModal("campaign"));
  one("[data-action=expedition]","click",()=>profileModal("expedition"));
  one("[data-action=simulator]","click",()=>{const s=createInitialState(`SIM-${Date.now()}`,"simulator");s.ui.route="simulator";store.replace(s);router.navigate("simulator")});
  one("[data-action=continue]","click",async()=>{try{store.replace(await loadGame("autosave"));locale=store.getState().profile.language||locale;router.navigate(store.getState().ui.route||"agency")}catch(e){toast(e.message,"error")}});
  one("[data-action=saves]","click",saveModal);one("[data-action=settings]","click",settingsModal);
}

function profileModal(mode){modal(`
  <div class="eyebrow">GSEA · CREDENCIAL DE DIREÇÃO</div><h2>${mode==="expedition"?"Configurar expedição":"Assumir o PROJECT HAVEN"}</h2>
  <p class="muted">Sua identidade, dificuldade e seed serão registradas no histórico da missão.</p>
  <div class="form-row"><div class="field"><label for="director">Nome do diretor</label><input id="director" maxlength="36" value="Alex Silva"></div><div class="field"><label for="difficulty">Dificuldade</label><select id="difficulty"><option value="story">Narrativa</option><option value="standard" selected>Padrão</option><option value="simulation">Simulação</option><option value="hardcore">Sobrevivência</option></select></div></div>
  <div class="field" style="margin-top:.8rem"><label for="seed">Seed reproduzível</label><input id="seed" value="${mode==="expedition"?`EXP-${new Date().toISOString().slice(0,10)}`:"HAVEN-2047"}"></div>
  <div class="card-actions"><button data-close>${t("back")}</button><button class="primary" data-start>${t("confirm")}</button></div>`,()=>{
    one("[data-start]","click",()=>{const name=document.querySelector("#director").value.trim()||"Diretor(a)",seed=document.querySelector("#seed").value.trim()||"HAVEN-2047",difficulty=document.querySelector("#difficulty").value;const next=createInitialState(seed,mode);next.profile.directorName=name;next.profile.difficulty=difficulty;next.profile.language=locale;if(mode==="expedition"){const mod=(next.meta.rngState%25)-12;next.economy.available+=mod;next.agency.support=clamp(45-mod/2);next.logs.events[0].message=`Expedição procedural iniciada com seed ${seed}. Modificador orçamentário: ${mod}.`}store.replace(next);closeModal();router.navigate("agency");toast("Diretoria confirmada. A crise já começou.");audioCue("success")});
  });
}

function shell(route){const s=store.getState(),act=data.acts.find(a=>a.id===route)||data.acts[s.campaign.act]||data.acts[0];s.ui.route=route;app.innerHTML=`
  <div class="shell"><header class="topbar"><div class="brand"><div class="brand-mark">◌</div><div><strong>LAST HORIZON</strong><small>GSEA · ARK-01</small></div></div>
  <div class="resource-strip">${resource(t("budget"),money(s.economy.available))}${resource(t("days"),`${s.time.earthDate} d`)}${resource(t("reliability"),pct(s.ship.reliability))}${resource(t("morale"),pct(s.crew.morale))}${resource(t("science"),s.science.points)}${resource(t("earth"),pct(100-s.time.earthDate/9))}</div>
  <div class="top-actions"><button data-save aria-label="${t("save")}">▣</button><button data-menu>${t("menu")}</button></div></header>
  <div class="workarea"><nav class="sidebar" aria-label="Atos da campanha"><ol class="nav-list">${data.acts.map((a,i)=>`<li><button data-route="${a.id}" class="${a.id===route?"active":""}" ${i>s.campaign.act+1?"disabled":""}><span class="nav-num">${a.n}</span><span>${a.title}</span></button></li>`).join("")}<li><button data-route="memorial"><span class="nav-num">∞</span><span>Memorial</span></button></li></ol></nav>
  <main class="mainview" id="mainview">${view(route,s,act)}</main>
  <aside class="intel"><section class="intel-section"><div class="aura-head"><div class="aura-orb"></div><div><div class="eyebrow">${t("aura")}</div><small class="muted">confiança ${s.ui.auraConfidence}%</small></div></div><p class="aura-message">${esc(act?.aura||"Tenho acesso aos registros causais e às margens atuais. A decisão permanece humana.")}</p><div class="decision-stack" id="context-actions"></div></section>
  <section class="intel-section"><h3>${t("log")}</h3><div class="log">${s.logs.events.slice(0,7).map(e=>`<div><time>${logTime(e.at)}</time> ${esc(e.message)}</div>`).join("")}</div></section></aside></div>
  <footer class="statusbar"><span>${esc(s.profile.directorName)} · ${esc(s.profile.difficulty.toUpperCase())}</span><span>SEED ${esc(s.meta.seed)} · ${navigator.onLine?"ENLACE LOCAL":"MODO OFFLINE"}</span></footer></div>`;
  bindShell(route,s);
}

const resource=(label,value)=>`<div class="resource"><span>${esc(label)}</span><b>${esc(value)}</b></div>`;
const head=(act,kicker="CAMPANHA PROJECT HAVEN")=>`<header class="screen-head"><div><div class="eyebrow">${kicker} · ATO ${act.n}</div><h1>${act.title}</h1></div><p>${act.subtitle}</p></header><div class="timeline">${data.acts.slice(0,10).map((_,i)=>`<i class="${i<store.getState().campaign.act?"done":i===store.getState().campaign.act?"current":""}"></i>`).join("")}</div>`;
function view(route,s,act){return ({agency,design,testing,crew,countdown,flight,cruise,science,landing,colony,governance,memorial,simulator}[route]||agency)(s,act)}

function agency(s,act){return `${head(act)}<section class="hero-panel"><div><div class="eyebrow">RELATÓRIO DE CRISE · 2047</div><h2>A convergência climática reduziu a janela de resposta global para menos de uma década.</h2></div></section><div class="grid grid-3">${data.departments.map(d=>`<article class="card"><h3>${d.name}</h3><p>${d.lead}<br>Capacidade técnica ${d.skill}%</p><div class="progress"><i style="--value:${d.skill}%"></i></div></article>`).join("")}</div><section class="panel panel-pad" style="margin-top:.8rem"><div class="panel-head"><div><h2>Primeira decisão pública</h2><p class="muted">Escolha como a GSEA apresentará o risco e financiará a reativação.</p></div><span class="chip warn">prazo ativo</span></div><div class="choice-grid"><button data-policy="transparent">Publicar evidências completas</button><button data-policy="controlled">Transparência por marcos</button><button data-policy="emergency">Mandato emergencial sigiloso</button></div></section>`}
function design(s,act){const categories={propulsion:"Propulsão",habitat:"Habitat",power:"Energia",shield:"Blindagem"};return `${head(act)}<div class="grid grid-4">${Object.entries(categories).map(([key,label])=>`<section class="panel panel-pad"><h3>${label}</h3>${data.components[key].map(c=>`<article class="card ${s.ship.design[key]===c.id?"selected":""}"><h3>${c.name}</h3><p>${c.desc}</p><small class="mono">${(c.mass/1000).toFixed(1)} t · ${c.cost} bi</small><button data-component="${key}:${c.id}">${s.ship.design[key]===c.id?"Selecionado":"Integrar"}</button></article>`).join("")}</section>`).join("")}</div><section class="panel panel-pad" style="margin-top:.8rem"><div class="grid grid-4">${metric("Massa",`${(s.ship.mass.total/1000).toFixed(1)} / 43 t`,s.ship.mass.total/s.ship.mass.limit*100)}${metric("Energia",`${s.ship.powerMargin} kW`,clamp(s.ship.powerMargin/6))}${metric("Térmica",`${s.ship.thermalMargin}%`,s.ship.thermalMargin)}${metric("Delta-v",`${s.ship.deltaV} m/s`,s.ship.deltaV/35)}</div><div class="card-actions"><button class="primary" data-approve-design ${s.ship.designValid?"":"disabled"}>Congelar configuração</button>${s.ship.designValid?'<span class="chip">margens válidas</span>':'<span class="chip danger">integração incompleta ou inválida</span>'}</div></section>`}
function testing(s,act){const completed=s.mission.testsCompleted||[];return `${head(act)}<div class="grid grid-3">${data.tests.map(test=>`<article class="card ${completed.includes(test.id)?"selected":""}"><h3>${test.name}</h3><p>Investiga: ${test.risk}</p><div class="mono">${test.cost} bi · ${test.days} dias · +${test.gain}% confiança</div><button data-test="${test.id}" ${completed.includes(test.id)?"disabled":""}>${completed.includes(test.id)?"Concluído":"Executar teste"}</button></article>`).join("")}</div><section class="panel panel-pad" style="margin-top:.8rem"><div class="panel-head"><h2>Registro de riscos</h2><span class="chip ${completed.length<4?"warn":""}">${completed.length}/6 executados</span></div>${s.ship.risks.length?`<table class="table"><thead><tr><th>Sistema</th><th>Causa</th><th>Estado</th></tr></thead><tbody>${s.ship.risks.map(r=>`<tr><td>${r.system}</td><td>${r.cause}</td><td class="risk-low">${r.severity}</td></tr>`).join("")}</tbody></table>`:'<p class="muted">Nenhuma evidência de defeito ainda. Ausência de evidência não é evidência de ausência.</p>'}<button class="primary" data-finish-tests ${completed.length>=4?"":"disabled"}>Certificar programa de testes</button></section>`}
function crew(s,act){return `${head(act)}<div class="grid grid-4">${data.crew.map(c=>`<article class="card ${s.crew.members.includes(c.id)?"selected":""}"><h3>${c.name}</h3><p>${c.role}<br>${c.trait}</p><div class="mono">HAB ${c.skill} · SAÚDE ${c.health}</div><button data-crew="${c.id}" ${!s.crew.members.includes(c.id)&&s.crew.members.length>=6?"disabled":""}>${s.crew.members.includes(c.id)?"Remover":"Selecionar"}</button></article>`).join("")}</div><section class="panel panel-pad" style="margin-top:.8rem"><div class="panel-head"><h2>Certificação coletiva</h2><span class="chip ${s.crew.members.length===6?"":"warn"}">${s.crew.members.length}/6 funções</span></div><div class="card-actions"><button data-train ${s.crew.members.length<6?"disabled":""}>Treinar 30 dias · 3 bi</button><button class="primary" data-finish-crew ${s.crew.members.length===6&&s.crew.training>=1?"":"disabled"}>Confirmar tripulação</button></div></section>`}
function countdown(s,act){const checks=[['Projeto integrado',s.mission.checklists.design],['Programa de testes',s.mission.checklists.tests],['Tripulação certificada',s.mission.checklists.crew],['Clima e corredor',s.time.earthDate<365]];return `${head(act)}<div class="flight-visual"></div><section class="panel panel-pad" style="margin-top:.8rem"><div class="panel-head"><div><h2>GO / NO-GO</h2><p class="muted">T− 00:09:42 · Complexo GSEA-12</p></div><span class="chip ${checks.every(c=>c[1])?"":"danger"}">${checks.every(c=>c[1])?"janela aberta":"risco elevado"}</span></div><div class="grid grid-4">${checks.map(([label,ok])=>`<div class="metric"><span>${label}</span><strong class="${ok?"risk-low":"risk-high"}">${ok?"GO":"NO-GO"}</strong></div>`).join("")}</div><div class="card-actions"><button data-hold>Suspender e revisar</button><button class="primary" data-launch>Autorizar lançamento</button></div></section>`}
function flight(s,act){const stages=["Ignição","Max-Q","Separação","Órbita","Queima de partida"],stage=s.mission.flightStage||0;return `${head(act)}<div class="flight-visual"></div><div class="instrument-grid" style="margin-top:.7rem">${gauge("EMPUXO",`${stage?Math.max(0,100-stage*12):0}%`)}${gauge("ALTITUDE",`${stage*143} km`)}${gauge("VELOCIDADE",`${(stage*2.21).toFixed(2)} km/s`)}${gauge("CARGA G",`${stage?Math.max(0.6,3.2-stage*.4).toFixed(1):"1.0"} g`)}${gauge("ESTRUTURA",pct(s.ship.integrity),s.ship.integrity<70)}${gauge("ENLACE",pct(s.systems.comms.linkQuality))}</div><section class="panel panel-pad" style="margin-top:.7rem"><h2>${stages[Math.min(stage,stages.length-1)]}</h2><p class="muted">A telemetria é calculada a partir da configuração, testes e seed da campanha.</p><button class="primary" data-flight-step>${stage>=4?"Confirmar rota interestelar":"Executar próxima fase"}</button></section>`}
function cruise(s,act){return `${head(act)}<div class="grid grid-4">${metric("Trajeto",pct(s.mission.route.progress),s.mission.route.progress)}${metric("Água",pct(s.systems.lifeSupport.waterPercent),s.systems.lifeSupport.waterPercent)}${metric("Alimento",`${Math.round(s.systems.lifeSupport.foodDays)} dias`,s.systems.lifeSupport.foodDays/16.8)}${metric("Integridade",pct(s.ship.integrity),s.ship.integrity)}</div><section class="panel panel-pad" style="margin-top:.8rem"><div class="panel-head"><div><h2>Relógio de missão</h2><p class="muted">${(s.time.missionHours/8760).toFixed(1)} anos desde a partida · alertas críticos interrompem a aceleração</p></div><span class="chip">x 1 ano</span></div><button class="primary" data-advance-cruise ${s.campaign.flags.arrived?"disabled":""}>Avançar um ano</button>${s.campaign.flags.arrived?'<button data-arrival>Entrar no sistema-alvo</button>':""}</section>`}
function science(s,act){return `${head(act)}<div class="grid grid-3">${data.planets.map(p=>{const scan=s.science.targets[p.id]||{confidence:0,habitability:0};return `<article class="panel panel-pad planet-card" data-planet="${p.id}"><div class="planet-orb"></div><div class="panel-head"><div><h2>${p.name}</h2><p class="muted">${p.desc}</p></div><span class="chip ${scan.confidence<60?"warn":""}">${scan.confidence}% dados</span></div><div class="grid grid-2"><div class="metric"><span>Habitabilidade</span><strong>${scan.habitability}</strong></div><div class="metric"><span>Risco</span><strong style="font-size:.72rem">${p.risk}</strong></div></div><div class="card-actions"><button data-scan="${p.id}">Lançar sonda · 1 ciclo</button><button class="primary" data-target="${p.id}" ${scan.confidence<68?"disabled":""}>Escolher destino</button></div></article>`}).join("")}</div>`}
function landing(s,act){return `${head(act)}<div class="flight-visual"></div><div class="grid grid-3" style="margin-top:.8rem"><article class="card"><h3>Vale Boreal</h3><p>Gelo subsuperficial abundante, relevo complexo e ventos catabáticos.</p><button data-site="boreal">Selecionar</button></article><article class="card"><h3>Delta Meridiano</h3><p>Planície estável, água distante e ótima margem de abortagem.</p><button data-site="delta">Selecionar</button></article><article class="card"><h3>Cratera Íris</h3><p>Minerais raros, sombra permanente e comunicações limitadas.</p><button data-site="iris">Selecionar</button></article></div><section class="panel panel-pad" style="margin-top:.8rem"><h2>Sequência EDL</h2><p class="muted">Escudo → sustentação → radar → retropropulsão → contato</p><button class="primary" data-touchdown ${s.mission.route.site?"":"disabled"}>Iniciar descida para ${esc(s.mission.route.site||"—")}</button></section>`}
function colony(s,act){return `${head(act)}<div class="grid grid-4">${metric("Materiais",s.colony.resources.materials,s.colony.resources.materials)}${metric("Energia",`${s.colony.resources.power} kW`,clamp(s.colony.resources.power/3))}${metric("Água",s.colony.resources.water,s.colony.resources.water)}${metric("Mão de obra",s.colony.resources.labor,s.colony.resources.labor)}</div><div class="grid grid-3" style="margin-top:.8rem">${data.buildings.map(b=>`<article class="card ${s.colony.buildings.includes(b.id)?"selected":""}"><h3>${b.name}</h3><p>${b.effect}</p><div class="mono">${b.cost} mat · ${b.labor} trab · ${b.power>0?"+":""}${b.power} kW</div><button data-building="${b.id}" ${s.colony.buildings.includes(b.id)?"disabled":""}>${s.colony.buildings.includes(b.id)?"Operacional":"Construir"}</button></article>`).join("")}</div><button class="primary" data-found ${["surface-hab","surface-reactor","water-extractor","colony-greenhouse"].every(id=>s.colony.buildings.includes(id))?"":"disabled"}>Convocar conselho da colônia</button>`}
function governance(s,act){return `${head(act)}<div class="grid grid-3"><article class="card ${s.colony.governance.policy==="earth"?"selected":""}"><h3>Mandato da Terra</h3><p>Manter a GSEA como autoridade e preparar nova migração.</p><button data-governance="earth">Adotar</button></article><article class="card ${s.colony.governance.policy==="council"?"selected":""}"><h3>Conselho Híbrido</h3><p>Dividir autoridade entre especialistas, colonos e Terra.</p><button data-governance="council">Adotar</button></article><article class="card ${s.colony.governance.policy==="independent"?"selected":""}"><h3>Autonomia Planetária</h3><p>Declarar soberania e responsabilidade integral pelo futuro local.</p><button data-governance="independent">Adotar</button></article></div><section class="panel panel-pad" style="margin-top:.8rem"><h2>Pesquisa e legado</h2><div class="choice-grid">${data.research.map(r=>{const done=s.colony.research.includes(r.id),ready=r.requires.every(x=>s.colony.research.includes(x));return `<button data-research="${r.id}" ${done||!ready||s.science.points<r.cost?"disabled":""}>${r.name} · ${r.cost} ciência<br><small>${r.effect}</small></button>`}).join("")}</div><div class="card-actions"><button data-contact>Investigar sinal coerente · 20 ciência</button><button class="primary" data-ending ${s.colony.governance.policy?"":"disabled"}>Calcular legado</button></div></section>`}
function memorial(s,act){return `<header class="screen-head"><div><div class="eyebrow">ARQUIVO GSEA</div><h1>Museu e Memorial</h1></div><p>Toda falha preserva sua cadeia causal. Nenhuma perda é resumida como azar.</p></header><div class="grid grid-2"><section class="panel panel-pad"><h2>Falhas e investigações</h2>${s.logs.failures.length?s.logs.failures.map(f=>`<article class="card"><h3>${f.cause}</h3><p><b>Sintomas:</b> ${f.symptoms.join(", ")}<br><b>Propagação:</b> ${f.propagation}<br><b>Detecção:</b> ${f.detection}<br><b>Mitigação:</b> ${f.mitigation}</p></article>`).join(""):'<p class="muted">Nenhuma ocorrência crítica registrada nesta linha temporal.</p>'}</section><section class="panel panel-pad"><h2>Decisões do diretor</h2>${s.campaign.decisions.map(d=>`<article class="card"><h3>${esc(d.title)}</h3><p>${esc(d.detail)}</p></article>`).join("")||'<p class="muted">O arquivo será preenchido por decisões irreversíveis.</p>'}</section></div>`}
function simulator(s){return `<header class="screen-head"><div><div class="eyebrow">LABORATÓRIO LIVRE</div><h1>Simulador de Sistemas</h1></div><p>Injete falhas e observe sintomas, propagação e mitigação sem consequências na campanha.</p></header><div class="instrument-grid">${gauge("PRESSÃO",`${s.systems.lifeSupport.cabinPressure.toFixed(1)} kPa`,s.systems.lifeSupport.cabinPressure<95)}${gauge("OXIGÊNIO",`${s.systems.lifeSupport.oxygenPercent.toFixed(1)}%`,s.systems.lifeSupport.oxygenPercent<19.5)}${gauge("CO₂",`${Math.round(s.systems.lifeSupport.co2ppm)} ppm`,s.systems.lifeSupport.co2ppm>1500)}${gauge("BATERIA",pct(s.systems.power.batterySoc),s.systems.power.batterySoc<25)}${gauge("NÚCLEO",`${s.systems.thermal.coreTemp} °C`,s.systems.thermal.coreTemp>900)}${gauge("CASCO",pct(s.ship.integrity),s.ship.integrity<70)}</div><section class="panel panel-pad" style="margin-top:.8rem"><h2>Injeção causal</h2><div class="choice-grid"><button data-failure="co2">Saturar filtro de CO₂</button><button data-failure="power">Perder barramento B</button><button data-failure="thermal">Travar radiador</button><button data-failure="hull">Impacto de micrometeoro</button></div><div class="card-actions"><button class="primary" data-mitigate>Executar mitigação recomendada</button><button data-reset-sim>Restaurar cenário</button></div></section>`}
const metric=(label,value,progress)=>`<div class="metric"><span>${label}</span><strong>${value}</strong><div class="progress ${progress<20?"danger":progress<40?"warn":""}"><i style="--value:${clamp(progress)}%"></i></div></div>`;
const gauge=(label,value,critical=false)=>`<div class="gauge ${critical?"critical":""}"><div class="gauge-value">${value}</div><div class="gauge-label">${label}</div></div>`;

function bindShell(route,s){
  document.querySelectorAll("[data-route]").forEach(b=>b.addEventListener("click",()=>router.navigate(b.dataset.route)));
  one("[data-menu]","click",()=>router.navigate("menu"));one("[data-save]","click",async()=>{await saveGame("autosave",store.getState());localStorage.setItem("lh-has-save","1");toast("Autosave confirmado");audioCue("success")});
  const go=(nextAct,nextRoute,title,detail)=>{store.update(x=>{x.campaign.act=Math.max(x.campaign.act,nextAct);x.campaign.decisions.push({title,detail});x.ui.route=nextRoute},title);router.navigate(nextRoute)};
  document.querySelectorAll("[data-policy]").forEach(b=>b.addEventListener("click",()=>{const p=b.dataset.policy;store.update(x=>{x.campaign.flags.publicPolicy=p;if(p==="transparent"){x.agency.support+=15;x.agency.politicalCapital-=5}else if(p==="controlled"){x.agency.support+=7;x.economy.available+=6}else{x.economy.available+=16;x.agency.support-=8}x.campaign.act=1;x.campaign.decisions.push({title:"Política de transparência",detail:p})},"Mandato de reativação aprovado");router.navigate("design")}));
  document.querySelectorAll("[data-component]").forEach(b=>b.addEventListener("click",()=>{const [category,id]=b.dataset.component.split(":"),next=data.components[category].find(c=>c.id===id),current=store.getState(),previous=data.components[category].find(c=>c.id===current.ship.design[category]),refund=previous?.cost||0;if(current.economy.available+refund<next.cost)return toast("Orçamento insuficiente para este componente.","error");store.update(x=>{x.economy.available+=refund-next.cost;x.economy.committed+=next.cost-refund;x.ship.design[category]=id},`${category}: ${id} integrado por ${next.cost} bi`)}));
  one("[data-approve-design]","click",()=>go(2,"testing","Configuração ARK-01 congelada",`${(s.ship.mass.total/1000).toFixed(1)} t; ${s.ship.deltaV} m/s delta-v`));
  document.querySelectorAll("[data-test]").forEach(b=>b.addEventListener("click",()=>{const test=data.tests.find(x=>x.id===b.dataset.test);let defect=false;store.update(x=>{defect=completeTest(x,test)},`Teste concluído: ${test.name}${defect?"; desvio detectado e mitigado":"; dentro dos limites"}`);toast(defect?"O teste revelou um modo de falha. Mitigação registrada.":"Teste nominal. Incerteza reduzida.",defect?"error":"ok")}));
  one("[data-finish-tests]","click",()=>go(3,"crew","Certificação de ensaios",`${(s.mission.testsCompleted||[]).length} campanhas concluídas`));
  document.querySelectorAll("[data-crew]").forEach(b=>b.addEventListener("click",()=>store.update(x=>{const id=b.dataset.crew,i=x.crew.members.indexOf(id);if(i>=0)x.crew.members.splice(i,1);else if(x.crew.members.length<6)x.crew.members.push(id)},`Quadro de voo atualizado`)));
  one("[data-train]","click",()=>store.update(x=>{if(x.economy.available>=3){x.economy.available-=3;x.time.earthDate+=30;x.crew.training++;x.crew.trust+=6;x.crew.morale+=3}},"Simulação integrada de 30 dias concluída"));
  one("[data-finish-crew]","click",()=>go(4,"countdown","Tripulação certificada",`${s.crew.members.length} especialistas; confiança ${Math.round(s.crew.trust)}%`));
  one("[data-hold]","click",()=>{store.update(x=>{x.time.earthDate+=12;x.ship.reliability+=3;x.agency.support-=3},"Lançamento suspenso para revisão independente");toast("Janela renegociada. A confiabilidade aumentou.")});
  one("[data-launch]","click",()=>{let result;store.update(x=>{result=simulateLaunch(x);x.campaign.decisions.push({title:"Autoridade de lançamento",detail:`Risco causal estimado ${result?.risk||0}%`})},"Sequência de lançamento autorizada");if(result.failed){audioCue("alarm");failureModal()}else{audioCue("success");store.update(x=>{x.campaign.act=5;x.mission.flightStage=1},"Liftoff confirmado");router.navigate("flight")}});
  one("[data-flight-step]","click",()=>{const stage=s.mission.flightStage||0;if(stage>=4){go(6,"cruise","Partida interestelar","Queima concluída e rota estabilizada")}else store.update(x=>{x.mission.flightStage=(x.mission.flightStage||0)+1;x.time.missionHours+=2;x.systems.propulsion.fuelPct-=3},`Fase de voo ${stage+1} concluída`)});
  one("[data-advance-cruise]","click",()=>{let event;store.update(x=>event=advanceCruise(x,data),"Um ano de cruzeiro concluído");eventModal(event)});one("[data-arrival]","click",()=>go(7,"science","Chegada ao sistema HAVEN",`${(s.time.missionHours/8760).toFixed(1)} anos de trânsito`));
  document.querySelectorAll("[data-scan]").forEach(b=>b.addEventListener("click",()=>{const p=data.planets.find(x=>x.id===b.dataset.scan);let result;store.update(x=>result=scanPlanet(x,p),`Sonda retornou dados de ${p.name}: confiança ${result?.confidence||0}%`);audioCue("success")}));
  document.querySelectorAll("[data-target]").forEach(b=>b.addEventListener("click",()=>{const p=data.planets.find(x=>x.id===b.dataset.target);store.update(x=>{x.mission.route.target=p.id;x.campaign.act=8;x.campaign.decisions.push({title:"Destino planetário",detail:`${p.name}; risco principal: ${p.risk}`})},`Destino selecionado: ${p.name}`);router.navigate("landing")}));
  document.querySelectorAll("[data-site]").forEach(b=>b.addEventListener("click",()=>store.update(x=>x.mission.route.site=b.dataset.site,`Local de pouso selecionado: ${b.dataset.site}`)));
  one("[data-touchdown]","click",()=>{store.update(x=>{x.campaign.flags.landed=true;x.campaign.act=9;x.mission.phase="superfície";x.ship.integrity-=Math.max(0,75-x.ship.reliability)/4},"Contato confirmado. ARK-01 estabeleceu presença de superfície.");router.navigate("colony");audioCue("success")});
  document.querySelectorAll("[data-building]").forEach(b=>b.addEventListener("click",()=>{const building=data.buildings.find(x=>x.id===b.dataset.building);let ok=false;store.update(x=>ok=buildColony(x,building),ok?`Construção concluída: ${building.name}`:`Recursos insuficientes: ${building.name}`);toast(ok?`${building.name} operacional`:"Materiais ou mão de obra insuficientes",ok?"ok":"error")}));
  one("[data-found]","click",()=>go(10,"governance","Colônia fundada",`${s.colony.population.total} habitantes; ${s.colony.buildings.length} sistemas operacionais`));
  document.querySelectorAll("[data-governance]").forEach(b=>b.addEventListener("click",()=>store.update(x=>{x.colony.governance.policy=b.dataset.governance;x.campaign.endingScore.ethics=b.dataset.governance==="council"?82:b.dataset.governance==="earth"?66:58},`Governança adotada: ${b.dataset.governance}`)));
  document.querySelectorAll("[data-research]").forEach(b=>b.addEventListener("click",()=>{const r=data.research.find(x=>x.id===b.dataset.research);store.update(x=>{x.science.points-=r.cost;x.colony.research.push(r.id)},`Pesquisa concluída: ${r.name}`)}));
  one("[data-contact]","click",()=>{if(s.science.points<20)return toast("Ciência insuficiente para validar o sinal.","error");store.update(x=>{x.science.points-=20;x.campaign.flags.contact=true},"O sinal coerente respondeu ao protocolo GSEA");toast("Resposta confirmada. A definição da missão mudou.")});
  one("[data-ending]","click",()=>{const ending=endingFor(store.getState());store.update(x=>x.campaign.endingScore={...x.campaign.endingScore,...ending.scores},`Legado calculado: ${ending.title}`);renderEnding(ending)});
  document.querySelectorAll("[data-failure]").forEach(b=>b.addEventListener("click",()=>injectFailure(b.dataset.failure)));
  one("[data-mitigate]","click",mitigateFailure);one("[data-reset-sim]","click",()=>{const n=createInitialState(`SIM-${Date.now()}`,"simulator");n.ui.route="simulator";store.replace(n)});
}

function failureModal(){modal(`<div class="eyebrow">ABORTAGEM AUTOMÁTICA</div><h2>Empuxo assimétrico detectado</h2><p>A votação dos sensores P-3/P-4 apontou divergência de pressão. A propagação foi interrompida antes da estrutura primária.</p><div class="card"><h3>Cadeia causal</h3><p>Turbobomba → combustão instável → vibração longitudinal → comando de corte → separação segura.</p></div><button class="primary" data-recover>Investigar, corrigir e tentar nova janela</button>`,()=>one("[data-recover]","click",()=>{store.update(x=>{x.ship.reliability+=8;x.time.earthDate+=24;x.economy.available-=4;x.mission.phase="planejamento"},"Causa raiz mitigada após abortagem");closeModal();router.navigate("countdown")}))}
function eventModal(event){modal(`<div class="eyebrow">EVENTO DE CRUZEIRO</div><h2>${event.title}</h2><p>${event.body}</p><div class="choice-grid">${event.choices.map((c,i)=>`<button data-event-choice="${i}">${c.label}</button>`).join("")}</div>`,()=>document.querySelectorAll("[data-event-choice]").forEach(b=>b.addEventListener("click",()=>{const c=event.choices[+b.dataset.eventChoice];store.update(x=>applyEventChoice(x,c),`${event.title}: ${c.label}`);closeModal()})))}
function injectFailure(type){store.update(x=>{x.ui.simFailure=type;if(type==="co2")x.systems.lifeSupport.co2ppm=4900;if(type==="power")x.systems.power.batterySoc=18;if(type==="thermal")x.systems.thermal.coreTemp=1080;if(type==="hull"){x.ship.integrity=61;x.systems.lifeSupport.cabinPressure=91.5}x.logs.failures.unshift({cause:{co2:"Saturação do leito de hidróxido",power:"Curto no barramento B",thermal:"Atuador do radiador travado",hull:"Impacto de micrometeoro"}[type],factors:["desgaste","redundância parcial"],symptoms:["telemetria fora da faixa"],propagation:"Carga secundária ameaçada",detection:"Tendência e votação de sensores",mitigation:"Isolar, transferir carga e reparar"})},`Falha injetada: ${type}`);audioCue("alarm")}
function mitigateFailure(){store.update(x=>{const type=x.ui.simFailure;if(type==="co2")x.systems.lifeSupport.co2ppm=760;if(type==="power")x.systems.power.batterySoc=72;if(type==="thermal")x.systems.thermal.coreTemp=510;if(type==="hull"){x.ship.integrity=79;x.systems.lifeSupport.cabinPressure=100.7}x.ui.simFailure=null},"Procedimento de mitigação concluído");audioCue("success")}

function renderEnding(ending){app.innerHTML=`<main class="ending"><article><div class="eyebrow">EPÍLOGO · PROJECT HAVEN</div><h1>${ending.title}</h1><p>${ending.body}</p><div class="scoreline">${Object.entries(ending.scores).map(([k,v])=>`<span class="chip">${k} ${Math.round(v)}</span>`).join("")}</div><div class="card-actions" style="justify-content:center"><button data-memorial>Ver memorial</button><button class="primary" data-new-cycle>Nova linha temporal</button></div></article></main>`;one("[data-memorial]","click",()=>router.navigate("memorial"));one("[data-new-cycle]","click",()=>router.navigate("menu"));saveGame("autosave",store.getState())}
function settingsModal(){const s=store.getState();modal(`<div class="eyebrow">INTERFACE E ACESSIBILIDADE</div><h2>${t("settings")}</h2><div class="form-row"><div class="field"><label>Idioma</label><select id="lang"><option value="pt-BR" ${locale==="pt-BR"?"selected":""}>Português (Brasil)</option><option value="en" ${locale==="en"?"selected":""}>English</option><option value="es" ${locale==="es"?"selected":""}>Español</option></select></div><div class="field"><label>Áudio sintetizado</label><select id="audio"><option value="on" ${s.profile.audio?"selected":""}>Ativo</option><option value="off" ${!s.profile.audio?"selected":""}>Silencioso</option></select></div></div><div class="choice-grid" style="margin-top:.8rem"><label class="card"><input type="checkbox" id="contrast" ${s.profile.accessibility.highContrast?"checked":""}> Alto contraste</label><label class="card"><input type="checkbox" id="large" ${s.profile.accessibility.largeText?"checked":""}> Texto ampliado</label><label class="card"><input type="checkbox" id="motion" ${s.profile.accessibility.reduceMotion?"checked":""}> Reduzir movimento</label><label class="card"><input type="checkbox" id="colorblind" ${s.profile.accessibility.colorblind?"checked":""}> Paleta daltônica</label></div><button class="primary" data-apply-settings>Aplicar</button>`,()=>one("[data-apply-settings]","click",()=>{locale=document.querySelector("#lang").value;localStorage.setItem("lh-locale",locale);store.update(x=>{x.profile.language=locale;x.profile.audio=document.querySelector("#audio").value==="on";x.profile.accessibility={highContrast:document.querySelector("#contrast").checked,largeText:document.querySelector("#large").checked,reduceMotion:document.querySelector("#motion").checked,colorblind:document.querySelector("#colorblind").checked}},"Preferências de acessibilidade atualizadas");closeModal();router.navigate(router.current())}))}
async function saveModal(){const rows=await listSaves();modal(`<div class="eyebrow">ARQUIVO LOCAL CRIPTOGRAFICAMENTE VERIFICADO</div><h2>${t("saves")}</h2><div class="grid">${rows.map(r=>`<article class="card"><h3>${esc(r.name)}</h3><p>${new Date(r.updatedAt).toLocaleString()} · ${esc(r.payload?.profile?.directorName||"")}</p><div class="card-actions"><button data-load="${esc(r.slot)}">Carregar</button><button data-delete="${esc(r.slot)}" class="danger">Excluir</button></div></article>`).join("")||'<p class="muted">Nenhuma partida armazenada.</p>'}</div><div class="card-actions"><button data-save-slot>Salvar no slot 1</button><button data-export>Exportar JSON</button><label class="card" style="cursor:pointer">Importar JSON<input class="sr-only" type="file" id="import-save" accept="application/json"></label></div>`,()=>{
    document.querySelectorAll("[data-load]").forEach(b=>b.addEventListener("click",async()=>{try{store.replace(await loadGame(b.dataset.load));closeModal();router.navigate(store.getState().ui.route||"agency")}catch(e){toast(e.message,"error")}}));
    document.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",async()=>{if(confirm("Excluir este slot? A exportação externa não será afetada.")){await deleteSave(b.dataset.delete);closeModal();saveModal()}}));
    one("[data-save-slot]","click",async()=>{await saveGame("1",store.getState());localStorage.setItem("lh-has-save","1");closeModal();toast("Slot 1 salvo com checksum")});one("[data-export]","click",()=>exportGame(store.getState()));
    one("#import-save","change",async e=>{try{store.replace(await importGame(e.target.files[0]));closeModal();router.navigate(store.getState().ui.route||"agency");toast("Save importado e migrado") }catch(err){toast(err.message,"error")}});
  })}
function modal(content,onOpen){const wrap=document.createElement("div");wrap.className="modal-backdrop";wrap.innerHTML=`<section class="modal" role="dialog" aria-modal="true"><header><span></span><button data-close aria-label="Fechar">×</button></header>${content}</section>`;document.body.append(wrap);wrap.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>wrap.remove()));wrap.addEventListener("click",e=>{if(e.target===wrap)wrap.remove()});onOpen?.();wrap.querySelector("input,select,button")?.focus()}
function closeModal(){document.querySelector(".modal-backdrop")?.remove()}
function one(selector,event,handler){document.querySelector(selector)?.addEventListener(event,handler)}

function drawSpace(){const c=document.querySelector("#space-canvas"),ctx=c.getContext("2d"),dpr=Math.min(devicePixelRatio,2);c.width=innerWidth*dpr;c.height=innerHeight*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,innerWidth,innerHeight);const rand=i=>((i*9301+49297)%233280)/233280;for(let i=0;i<160;i++){const x=rand(i)*innerWidth,y=rand(i+251)*innerHeight,r=rand(i+13)*1.2+.2;ctx.fillStyle=`rgba(160,225,255,${.18+rand(i+99)*.55})`;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}}
addEventListener("resize",drawSpace);drawSpace();
store.subscribe(state=>{lastState=state;applyAccessibility(state);if(router.current()!=="menu")shell(router.current());clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>{saveGame("autosave",state);localStorage.setItem("lh-has-save","1")},650)});
const router=createRouter(route=>{if(route==="menu")menu();else if(route==="ending")renderEnding(endingFor(store.getState()));else shell(route)});
applyAccessibility(store.getState());router.start();
if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./service-worker.js").catch(()=>{});
